/* eslint-disable */
export const data =  [
  { empresa: "ALLIAR ON", ativo: "AALR3", tipo:"Ações" },
  { empresa: "ABC BRASIL PN", ativo: "ABCB4", tipo:"Ações" },
  { empresa: "GRAND PLAZA SHOPPING", ativo: "ABCP11", tipo:"Fundos Imobiliários" },
  { empresa: "AMBEV S/A ON", ativo: "ABEV3", tipo:"Ações" },
  { empresa: "CAMILA PN PN", ativo: "ACML4L", tipo:"Ações" },
  { empresa: "ADVANCED-DH ON", ativo: "ADHM1", tipo:"Ações" },
  { empresa: "ADVANCED-DH ON", ativo: "ADHM3", tipo:"Ações" },
  { empresa: "ADVANCED-DH ON", ativo: "ADHM9", tipo:"Ações" },
  { empresa: "AF INVEST RECEBÍVEIS IMOBILIÁRIOS", ativo: "AFCR11", tipo:"Fundos Imobiliários" },
  { empresa: "AFLUENTE ON", ativo: "AFLT3", tipo:"Ações" },
  { empresa: "ALIANZA FOFII", ativo: "AFOF11", tipo:"Fundos Imobiliários" },
  { empresa: "AGROPECUARIA BELO HORIZO... PNA", ativo: "AGBH5L", tipo:"Ações" },
  { empresa: "BRASIL AGRO ON", ativo: "AGRO3", tipo:"Ações" },
  { empresa: "AGROPECUARIA SERRA AZUL PNA", ativo: "AGSA5L", tipo:"Ações" },
  { empresa: "AGROPECUARIA SANTA ROSA PNA", ativo: "AGSR5L", tipo:"Ações" },
  { empresa: "AGRO INDUSTRIAL DE CEREA... PNA", ativo: "AGVE5L", tipo:"Ações" },
  { empresa: "AGRO INDUSTRIAL DE CEREA... PNB", ativo: "AGVE6L", tipo:"Ações" },
  { empresa: "SPTURIS ON", ativo: "AHEB1", tipo:"Ações" },
  { empresa: "SPTURIS PNA", ativo: "AHEB11", tipo:"Ações" },
  { empresa: "SPTURIS PNB", ativo: "AHEB13", tipo:"Ações" },
  { empresa: "SP TURISMO ON", ativo: "AHEB3", tipo:"Ações" },
  { empresa: "SP TURISMO PNA", ativo: "AHEB5", tipo:"Ações" },
  { empresa: "SP TURISMO PNB", ativo: "AHEB6", tipo:"Ações" },
  { empresa: "AUTONOMY EDIFÍCIOS CORPORATIVOS", ativo: "AIEC11", tipo:"Fundos Imobiliários" },
  { empresa: "AGROINDUSTRIAL E PASTORI... PNA", ativo: "AIPN5L", tipo:"Ações" },
  { empresa: "ALEF ON", ativo: "ALEF3B", tipo:"Ações" },
  { empresa: "TORRE ALMIRANTE", ativo: "ALMI11", tipo:"Fundos Imobiliários" },
  { empresa: "ALUMINIO EXTRUDADO BRASI... PN", ativo: "ALMN4L", tipo:"Ações" },
  { empresa: "ALUMAZON COMPONENTES AMA... PNA", ativo: "ALMZ5L", tipo:"Ações" },
  { empresa: "ALPARGATAS ON", ativo: "ALPA3", tipo:"Ações" },
  { empresa: "ALPARGATAS PN", ativo: "ALPA4", tipo:"Ações" },
  { empresa: "ALLPARK EMPREENDIMENTOS ... ON", ativo: "ALPK3", tipo:"Ações" },
  { empresa: "ALIANSCE SONAE ON", ativo: "ALSO3", tipo:"Ações" },
  { empresa: "ALUPAR ON", ativo: "ALUP3", tipo:"Ações" },
  { empresa: "ALUPAR PN", ativo: "ALUP4", tipo:"Ações" },
  { empresa: "ALIANZA TRUST RENDA IMOBILIÁRIA", ativo: "ALZR11", tipo:"Fundos Imobiliários" },
  { empresa: "LOJAS MARISA ON", ativo: "AMAR3", tipo:"Ações" },
  { empresa: "AMBIPAR PARTICIPACOES E ... ON", ativo: "AMBP3", tipo:"Ações" },
  { empresa: "ANCAR IC", ativo: "ANCR11B", tipo:"Fundos Imobiliários" },
  { empresa: "ANIMA ON", ativo: "ANIM3", tipo:"Ações" },
  { empresa: "APIACAS PNA PNA", ativo: "APAK5L", tipo:"Ações" },
  { empresa: "ALPER ON", ativo: "APER1", tipo:"Ações" },
  { empresa: "ALPER ON", ativo: "APER3", tipo:"Ações" },
  { empresa: "ALPER ON", ativo: "APER9", tipo:"Ações" },
  { empresa: "ALIPERTI ON", ativo: "APTI3", tipo:"Ações" },
  { empresa: "ALIPERTI PN", ativo: "APTI4", tipo:"Ações" },
  { empresa: "ÁQUILLA", ativo: "AQLL11", tipo:"Fundos Imobiliários" },
  { empresa: "RIZA ARCTIUM REAL ESTATE", ativo: "ARCT11", tipo:"Fundos Imobiliários" },
  { empresa: "AQ3 RENDA", ativo: "ARFI11B", tipo:"Fundos Imobiliários" },
  { empresa: "ÁTRIO REIT RECEBÍVEIS IMOBILIÁRIOS", ativo: "ARRI11", tipo:"Fundos Imobiliários" },
  { empresa: "AGROMASSA PNA PNA", ativo: "ARSA5L", tipo:"Ações" },
  { empresa: "AREZZO ON", ativo: "ARZZ3", tipo:"Ações" },
  { empresa: "HAZ FII", ativo: "ATCR11", tipo:"Fundos Imobiliários" },
  { empresa: "ATMA ON", ativo: "ATMP3", tipo:"Ações" },
  { empresa: "ATOMPAR ON", ativo: "ATOM3", tipo:"Ações" },
  { empresa: "HEDGE ATRIUM SHOPPING SANTO ANDRÉ", ativo: "ATSA11", tipo:"Fundos Imobiliários" },
  { empresa: "AZEVEDO ON", ativo: "AZEV3", tipo:"Ações" },
  { empresa: "AZEVEDO PN", ativo: "AZEV4", tipo:"Ações" },
  { empresa: "AMAZON GOLF PNA", ativo: "AZGT5L", tipo:"Ações" },
  { empresa: "AZUL PN", ativo: "AZUL4", tipo:"Ações" },
  { empresa: "B3 SA - BRASIL BOLSA BAL... ON", ativo: "B3SA3", tipo:"Ações" },
  { empresa: "BAHEMA EDUCAÇÃO ON", ativo: "BAHI3", tipo:"Ações" },
  { empresa: "BAHEMA ON", ativo: "BAHI9", tipo:"Ações" },
  { empresa: "BAUMER ON", ativo: "BALM3", tipo:"Ações" },
  { empresa: "BAUMER PN", ativo: "BALM4", tipo:"Ações" },
  { empresa: "BARIGUI RENDIMENTOS", ativo: "BARI11", tipo:"Fundos Imobiliários" },
  { empresa: "EXCELSIOR ON", ativo: "BAUH3", tipo:"Ações" },
  { empresa: "EXCELSIOR PN", ativo: "BAUH4", tipo:"Ações" },
  { empresa: "AMAZONIA ON", ativo: "BAZA3", tipo:"Ações" },
  { empresa: "BANCO DO BRASIL ON", ativo: "BBAS11", tipo:"Ações" },
  { empresa: "BANCO DO BRASIL ON", ativo: "BBAS12", tipo:"Ações" },
  { empresa: "BANCO DO BRASIL ON", ativo: "BBAS3", tipo:"Ações" },
  { empresa: "BRADESCO ON", ativo: "BBDC3", tipo:"Ações" },
  { empresa: "BRADESCO PN", ativo: "BBDC4", tipo:"Ações" },
  { empresa: "BB PROGRESSIVO", ativo: "BBFI11B", tipo:"Fundos Imobiliários" },
  { empresa: "BB RECEBÍVEIS IMOBILIÁRIOS", ativo: "BBIM11", tipo:"Fundos Imobiliários" },
  { empresa: "BBM LOGÍSTICA ON", ativo: "BBML3", tipo:"Ações" },
  { empresa: "BB PROGRESSIVO II", ativo: "BBPO11", tipo:"Fundos Imobiliários" },
  { empresa: "BB RENDA CORPORATIVA", ativo: "BBRC11", tipo:"Fundos Imobiliários" },
  { empresa: "BR BROKERS ON", ativo: "BBRK3", tipo:"Ações" },
  { empresa: "BB SEGURIDADE ON", ativo: "BBSE3", tipo:"Ações" },
  { empresa: "CIDADE JARDIM CONTINENTAL TOWER", ativo: "BBVJ11", tipo:"Fundos Imobiliários" },
  { empresa: "BTG PACTUAL FUNDO DE FUNDOS", ativo: "BCFF11", tipo:"Fundos Imobiliários" },
  { empresa: "FIBRA CIA SECURIT DE CRE...", ativo: "BCFF12", tipo:"Ações" },
  { empresa: "BRADESCO CARTEIRA IMOBILIÁRIA ATIVA", ativo: "BCIA11", tipo:"Fundos Imobiliários" },
  { empresa: "BRADESCO REAL ESTATE POR...", ativo: "BCIA12", tipo:"Ações" },
  { empresa: "BANESTES RECEBÍVEIS IMOBILIÁRIOS", ativo: "BCRI11", tipo:"Fundos Imobiliários" },
  { empresa: "BARDELLA ON", ativo: "BDLL3", tipo:"Ações" },
  { empresa: "BARDELLA PN", ativo: "BDLL4", tipo:"Ações" },
  { empresa: "BDRX", ativo: "BDRX11", tipo:"Ações" },
  { empresa: "MINERVA ON", ativo: "BEEF11", tipo:"Ações" },
  { empresa: "MINERVA ON", ativo: "BEEF3", tipo:"Ações" },
  { empresa: "BANESTES ON", ativo: "BEES3", tipo:"Ações" },
  { empresa: "BANESTES PN", ativo: "BEES4", tipo:"Ações" },
  { empresa: "BETAPART PARTICIPACOES ON", ativo: "BETP3B", tipo:"Ações" },
  { empresa: "BANESE ON", ativo: "BGIP3", tipo:"Ações" },
  { empresa: "BANESE PN", ativo: "BGIP4", tipo:"Ações" },
  { empresa: "INTER TÍTULOS IMOBILIÁRIOS", ativo: "BICR11", tipo:"Fundos Imobiliários" },
  { empresa: "BANCO INTER ON", ativo: "BIDI1", tipo:"Ações" },
  { empresa: "BANCO INTER", ativo: "BIDI12", tipo:"Ações" },
  { empresa: "BANCO INTER PN", ativo: "BIDI2", tipo:"Ações" },
  { empresa: "BANCO INTER ON", ativo: "BIDI3", tipo:"Ações" },
  { empresa: "BANCO INTER PN", ativo: "BIDI4", tipo:"Ações" },
  { empresa: "BIOMM ON", ativo: "BIOM1", tipo:"Ações" },
  { empresa: "BIOMM ON", ativo: "BIOM11", tipo:"Ações" },
  { empresa: "BIOMM ON", ativo: "BIOM3", tipo:"Ações" },
  { empresa: "BIOMM ON", ativo: "BIOM9", tipo:"Ações" },
  { empresa: "JS REAL ESTATE RECEBÍVEIS IMOBILIÁRIOS", ativo: "BJRC11", tipo:"Fundos Imobiliários" },
  { empresa: "BURGUER KING BRASIL ON", ativo: "BKBR3", tipo:"Ações" },
  { empresa: "BLUECAP RENDA LOGÍSTICA", ativo: "BLCP11", tipo:"Fundos Imobiliários" },
  { empresa: "BLUEMACAW OFFICE FUND II", ativo: "BLMO11", tipo:"Fundos Imobiliários" },
  { empresa: "BANCO MERCANTIL ON", ativo: "BMEB3", tipo:"Ações" },
  { empresa: "BANCO MERCANTIL PN", ativo: "BMEB4", tipo:"Ações" },
  { empresa: "BMG PN", ativo: "BMGB4", tipo:"Ações" },
  { empresa: "BRASÍLIO MACHADO", ativo: "BMII11", tipo:"Fundos Imobiliários" },
  { empresa: "MERC INVEST ON", ativo: "BMIN3", tipo:"Ações" },
  { empresa: "MERC INVEST PN", ativo: "BMIN4", tipo:"Ações" },
  { empresa: "BIC MONARK ON", ativo: "BMKS3", tipo:"Ações" },
  { empresa: "BM BRASCAN LAJES CORPORATIVAS", ativo: "BMLC11B", tipo:"Fundos Imobiliários" },
  { empresa: "BANCO NORDESTE ON", ativo: "BNBR3", tipo:"Ações" },
  { empresa: "BANRISUL NOVAS FRONTEIRAS", ativo: "BNFS11", tipo:"Fundos Imobiliários" },
  { empresa: "BOMBRIL ON", ativo: "BOBR3", tipo:"Ações" },
  { empresa: "BOMBRIL PN", ativo: "BOBR4", tipo:"Ações" },
  { empresa: "BTG PACTUAL PNA", ativo: "BPAC12", tipo:"Ações" },
  { empresa: "BTG PACTUAL ON", ativo: "BPAC3", tipo:"Ações" },
  { empresa: "BTG PACTUAL PNA", ativo: "BPAC5", tipo:"Ações" },
  { empresa: "BTG PACTUAL ON", ativo: "BPAC9", tipo:"Ações" },
  { empresa: "BANCO PAN PN", ativo: "BPAN10", tipo:"Ações" },
  { empresa: "BANCO PAN PN", ativo: "BPAN4", tipo:"Ações" },
  { empresa: "BANCO BANPARÁ ON", ativo: "BPAR3", tipo:"Ações" },
  { empresa: "BRASIL PLURAL ABSOLUTO FUNDO DE FUNDOS", ativo: "BPFF11", tipo:"Fundos Imobiliários" },
  { empresa: "BRIO PRIME MALLS", ativo: "BPMA11", tipo:"Fundos Imobiliários" },
  { empresa: "BTG PACTUAL SHOPPINGS", ativo: "BPML11", tipo:"Fundos Imobiliários" },
  { empresa: "BRLPROP", ativo: "BPRP11", tipo:"Fundos Imobiliários" },
  { empresa: "BRADESPAR ON", ativo: "BRAP3", tipo:"Ações" },
  { empresa: "BRADESPAR PN", ativo: "BRAP4", tipo:"Ações" },
  { empresa: "BRESCO LOGÍSTICA", ativo: "BRCO11", tipo:"Fundos Imobiliários" },
  { empresa: "BTG PACTUAL CORPORATE OFFICE FUND", ativo: "BRCR11", tipo:"Fundos Imobiliários" },
  { empresa: "PETROBRAS BR ON", ativo: "BRDT3", tipo:"Ações" },
  { empresa: "BRAZIL REAL ESTATE VICTORY FUND I", ativo: "BREV11", tipo:"Fundos Imobiliários" },
  { empresa: "BRF S/A ON", ativo: "BRFS3", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO PNE", ativo: "BRGE11", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO PNF", ativo: "BRGE12", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO ON", ativo: "BRGE3", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO PNA", ativo: "BRGE5", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO PNB", ativo: "BRGE6", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO PNC", ativo: "BRGE7", tipo:"Ações" },
  { empresa: "ALFA CONSORCIO PND", ativo: "BRGE8", tipo:"Ações" },
  { empresa: "BR HOTEIS", ativo: "BRHT11B", tipo:"Fundos Imobiliários" },
  { empresa: "BRIO REAL ESTATE II", ativo: "BRIM11", tipo:"Fundos Imobiliários" },
  { empresa: "ALFA INVEST ON", ativo: "BRIV3", tipo:"Ações" },
  { empresa: "ALFA INVEST PN", ativo: "BRIV4", tipo:"Ações" },
  { empresa: "BRASKEM ON", ativo: "BRKM3", tipo:"Ações" },
  { empresa: "BRASKEM PNA", ativo: "BRKM5", tipo:"Ações" },
  { empresa: "BRASKEM PNB", ativo: "BRKM6", tipo:"Ações" },
  { empresa: "BR MALLS PAR ON", ativo: "BRML3", tipo:"Ações" },
  { empresa: "BR PROPERT ON", ativo: "BRPR3", tipo:"Ações" },
  { empresa: "BRQ ON", ativo: "BRQB3", tipo:"Ações" },
  { empresa: "BANRISUL ON", ativo: "BRSR3", tipo:"Ações" },
  { empresa: "BANRISUL PNA", ativo: "BRSR5", tipo:"Ações" },
  { empresa: "BANRISUL PNB", ativo: "BRSR6", tipo:"Ações" },
  { empresa: "BIOSEV ON", ativo: "BSEV3", tipo:"Ações" },
  { empresa: "BRB BANCO ON", ativo: "BSLI3", tipo:"Ações" },
  { empresa: "BRB BANCO PN", ativo: "BSLI4", tipo:"Ações" },
  { empresa: "BTG PACTUAL CRÉDITO IMOBILIÁRIO", ativo: "BTCR11", tipo:"Fundos Imobiliários" },
  { empresa: "BTG PACTUAL LOGÍSTICA", ativo: "BTLG11", tipo:"Fundos Imobiliários" },
  { empresa: "B2W DIGITAL ON", ativo: "BTOW1", tipo:"Ações" },
  { empresa: "B2W DIGITAL ON", ativo: "BTOW3", tipo:"Ações" },
  { empresa: "BTSP I", ativo: "BTSG11", tipo:"Fundos Imobiliários" },
  { empresa: "BATTISTELLA ON", ativo: "BTTL3", tipo:"Ações" },
  { empresa: "BRASIL VAREJO", ativo: "BVAR11", tipo:"Fundos Imobiliários" },
  { empresa: "BRAZIL REALTY", ativo: "BZLI11", tipo:"Fundos Imobiliários" },
  { empresa: "CABINDA PARTICIPACOES ON", ativo: "CABI3B", tipo:"Ações" },
  { empresa: "CACONDE PARTICIPACOES ON", ativo: "CACO3B", tipo:"Ações" },
  { empresa: "CAIANDA PARTICIPACOES ON", ativo: "CAIA3B", tipo:"Ações" },
  { empresa: "CONSTRUTORA ADOLFO L ON", ativo: "CALI3", tipo:"Ações" },
  { empresa: "CONSTRUTORA ADOLFO L PN", ativo: "CALI4", tipo:"Ações" },
  { empresa: "CAMBUCI ON", ativo: "CAMB3", tipo:"Ações" },
  { empresa: "CAMBUCI PN", ativo: "CAMB4", tipo:"Ações" },
  { empresa: "CAMIL ALIMENTOS ON", ativo: "CAML3", tipo:"Ações" },
  { empresa: "ANDRADE GUTIERREZ PARTIC... ON", ativo: "CANT3", tipo:"Ações" },
  { empresa: "ANDRADE GUTIERREZ PARTIC... ON", ativo: "CANT3B", tipo:"Ações" },
  { empresa: "ANDRADE GUTIERREZ PARTIC... PN", ativo: "CANT4", tipo:"Ações" },
  { empresa: "ANDRADE GUTIERREZ PARTIC... PN", ativo: "CANT4B", tipo:"Ações" },
  { empresa: "CSU CARDSYSTEM ON", ativo: "CARD3", tipo:"Ações" },
  { empresa: "BRAZILIAN GRAVEYARDDEATH CARE", ativo: "CARE11", tipo:"Fundos Imobiliários" },
  { empresa: "CASAN ON", ativo: "CASN1", tipo:"Ações" },
  { empresa: "CASAN PN", ativo: "CASN2", tipo:"Ações" },
  { empresa: "CASAN ON", ativo: "CASN3", tipo:"Ações" },
  { empresa: "CASAN PN", ativo: "CASN4", tipo:"Ações" },
  { empresa: "IND CATAGUAS ON", ativo: "CATA3", tipo:"Ações" },
  { empresa: "IND CATAGUAS PN", ativo: "CATA4", tipo:"Ações" },
  { empresa: "AMPLA ENERG ON", ativo: "CBEE3", tipo:"Ações" },
  { empresa: "CASTELLO BRANCO OFFICE PARK", ativo: "CBOP11", tipo:"Fundos Imobiliários" },
  { empresa: "CENO NORTE PNA PNA", ativo: "CCNO5L", tipo:"Ações" },
  { empresa: "CYRELA COMMERCIAL PROP ON", ativo: "CCPR3", tipo:"Ações" },
  { empresa: "CCR ON", ativo: "CCRO3", tipo:"Ações" },
  { empresa: "CCX CARVAO ON", ativo: "CCXC3", tipo:"Ações" },
  { empresa: "C&A ON", ativo: "CEAB3", tipo:"Ações" },
  { empresa: "CEB ON", ativo: "CEBR3", tipo:"Ações" },
  { empresa: "CEB PNA", ativo: "CEBR5", tipo:"Ações" },
  { empresa: "CEB PNB", ativo: "CEBR6", tipo:"Ações" },
  { empresa: "CEDRO ON", ativo: "CEDO3", tipo:"Ações" },
  { empresa: "CEDRO PN", ativo: "CEDO4", tipo:"Ações" },
  { empresa: "COELBA ON", ativo: "CEEB3", tipo:"Ações" },
  { empresa: "COELBA PNA", ativo: "CEEB5", tipo:"Ações" },
  { empresa: "COELBA PNB", ativo: "CEEB6", tipo:"Ações" },
  { empresa: "CEEE-D ON", ativo: "CEED3", tipo:"Ações" },
  { empresa: "CEEE-D PN", ativo: "CEED4", tipo:"Ações" },
  { empresa: "CEG ON", ativo: "CEGR3", tipo:"Ações" },
  { empresa: "CELPA ON", ativo: "CELP3", tipo:"Ações" },
  { empresa: "CELPA PNA", ativo: "CELP5", tipo:"Ações" },
  { empresa: "CELPA PNB", ativo: "CELP6", tipo:"Ações" },
  { empresa: "CELPA PNC", ativo: "CELP7", tipo:"Ações" },
  { empresa: "CEO CYRELA COMMERCIAL PROPERTIES", ativo: "CEOC11", tipo:"Fundos Imobiliários" },
  { empresa: "CELPE ON", ativo: "CEPE3", tipo:"Ações" },
  { empresa: "CELPE PNA", ativo: "CEPE5", tipo:"Ações" },
  { empresa: "CELPE PNB", ativo: "CEPE6", tipo:"Ações" },
  { empresa: "CESP ON", ativo: "CESP3", tipo:"Ações" },
  { empresa: "CESP PNA", ativo: "CESP5", tipo:"Ações" },
  { empresa: "CESP PNB", ativo: "CESP6", tipo:"Ações" },
  { empresa: "COMGÁS ON", ativo: "CGAS3", tipo:"Ações" },
  { empresa: "COMGÁS PNA", ativo: "CGAS5", tipo:"Ações" },
  { empresa: "GRAZZIOTIN ON", ativo: "CGRA3", tipo:"Ações" },
  { empresa: "GRAZZIOTIN PN", ativo: "CGRA4", tipo:"Ações" },
  { empresa: "CIAGRA CIA AGROPASTORIAL... PNB", ativo: "CIAG6L", tipo:"Ações" },
  { empresa: "CIELO ON", ativo: "CIEL3", tipo:"Ações" },
  { empresa: "CJ FII", ativo: "CJFI11", tipo:"Fundos Imobiliários" },
  { empresa: "CELESC ON", ativo: "CLSC3", tipo:"Ações" },
  { empresa: "CELESC PN", ativo: "CLSC4", tipo:"Ações" },
  { empresa: "CEMIG ON", ativo: "CMIG3", tipo:"Ações" },
  { empresa: "CEMIG PN", ativo: "CMIG4", tipo:"Ações" },
  { empresa: "CIMS ON", ativo: "CMSA3", tipo:"Ações" },
  { empresa: "CIMS PN", ativo: "CMSA4", tipo:"Ações" },
  { empresa: "CENESP", ativo: "CNES11", tipo:"Fundos Imobiliários" },
  { empresa: "CINESYSTEM ON", ativo: "CNSY3", tipo:"Ações" },
  { empresa: "CENTAURO ON", ativo: "CNTO3", tipo:"Ações" },
  { empresa: "COELCE ON", ativo: "COCE3", tipo:"Ações" },
  { empresa: "COELCE PNA", ativo: "COCE5", tipo:"Ações" },
  { empresa: "COELCE PNB", ativo: "COCE6", tipo:"Ações" },
  { empresa: "COGNA ON", ativo: "COGN3", tipo:"Ações" },
  { empresa: "COR RIBEIRO ON", ativo: "CORR3", tipo:"Ações" },
  { empresa: "COR RIBEIRO PN", ativo: "CORR4", tipo:"Ações" },
  { empresa: "CPFL ENERGIA ON", ativo: "CPFE3", tipo:"Ações" },
  { empresa: "CAPITÂNIA REIT FOF", ativo: "CPFF11", tipo:"Fundos Imobiliários" },
  { empresa: "COPEL ON", ativo: "CPLE3", tipo:"Ações" },
  { empresa: "COPEL PNA", ativo: "CPLE5", tipo:"Ações" },
  { empresa: "COPEL PNB", ativo: "CPLE6", tipo:"Ações" },
  { empresa: "CPFL RENOVÁVEL ON", ativo: "CPRE3", tipo:"Ações" },
  { empresa: "CPFL RENOVÁVEL ON", ativo: "CPRE3L", tipo:"Ações" },
  { empresa: "CAPITALPART PARTICIPACOES ON", ativo: "CPTP3B", tipo:"Ações" },
  { empresa: "CAPITÂNIA SECURITIES II", ativo: "CPTS11", tipo:"Fundos Imobiliários" },
  { empresa: "FII CAPI SEC CI MB", ativo: "CPTS12B", tipo:"Ações" },
  { empresa: "CR2 ON", ativo: "CRDE3", tipo:"Ações" },
  { empresa: "CARREFOUR ON", ativo: "CRFB3", tipo:"Ações" },
  { empresa: "CAIXA RIO BRAVO FUNDO DE FUNDOS II", ativo: "CRFF11", tipo:"Fundos Imobiliários" },
  { empresa: "ALFA FINANC ON", ativo: "CRIV3", tipo:"Ações" },
  { empresa: "ALFA FINANC PN", ativo: "CRIV4", tipo:"Ações" },
  { empresa: "CRISTAL ON", ativo: "CRPG3", tipo:"Ações" },
  { empresa: "CRISTAL PNA", ativo: "CRPG5", tipo:"Ações" },
  { empresa: "CRISTAL PNB", ativo: "CRPG6", tipo:"Ações" },
  { empresa: "CONCESSIONARIA RIO TERES... ON", ativo: "CRTE3B", tipo:"Ações" },
  { empresa: "CONCESSIONARIA RIO TERES... PNA", ativo: "CRTE5B", tipo:"Ações" },
  { empresa: "DON CAROLINA PNA PNA", ativo: "CRVD5L", tipo:"Ações" },
  { empresa: "SEG AL BAHIA ON", ativo: "CSAB3", tipo:"Ações" },
  { empresa: "SEG AL BAHIA PN", ativo: "CSAB4", tipo:"Ações" },
  { empresa: "COSAN ON", ativo: "CSAN3", tipo:"Ações" },
  { empresa: "COPASA ON", ativo: "CSMG3", tipo:"Ações" },
  { empresa: "SID NACIONAL ON", ativo: "CSNA3", tipo:"Ações" },
  { empresa: "COSERN ON", ativo: "CSRN3", tipo:"Ações" },
  { empresa: "COSERN PNA", ativo: "CSRN5", tipo:"Ações" },
  { empresa: "COSERN PNB", ativo: "CSRN6", tipo:"Ações" },
  { empresa: "CEPAC-CTBA CPA MB", ativo: "CTBA11B", tipo:"Ações" },
  { empresa: "CEPAC - CTBA", ativo: "CTBA11BL", tipo:"Ações" },
  { empresa: "CTC CENTRO DE TECNOLOGIA... ON", ativo: "CTCA3", tipo:"Ações" },
  { empresa: "KARSTEN ON", ativo: "CTKA3", tipo:"Ações" },
  { empresa: "KARSTEN PN", ativo: "CTKA4", tipo:"Ações" },
  { empresa: "COTEMINAS ON", ativo: "CTNM3", tipo:"Ações" },
  { empresa: "COTEMINAS PN", ativo: "CTNM4", tipo:"Ações" },
  { empresa: "CENTENOR EMPREENDIMENTOS PNE", ativo: "CTNR11L", tipo:"Ações" },
  { empresa: "SANTANENSE ON", ativo: "CTSA3", tipo:"Ações" },
  { empresa: "SANTANENSE PN", ativo: "CTSA4", tipo:"Ações" },
  { empresa: "SANTANENSE PND", ativo: "CTSA8", tipo:"Ações" },
  { empresa: "SAO FRANCISCO TEXTIL PNA", ativo: "CTVL5L", tipo:"Ações" },
  { empresa: "CENTRO TÊXTIL INTERNACIONAL", ativo: "CTXT11", tipo:"Fundos Imobiliários" },
  { empresa: "VBI CRI", ativo: "CVBI11", tipo:"Fundos Imobiliários" },
  { empresa: "CVC BRASIL ON", ativo: "CVCB1", tipo:"Ações" },
  { empresa: "CVC BRASIL ON", ativo: "CVCB3", tipo:"Ações" },
  { empresa: "CAIXA CEDAE", ativo: "CXCE11B", tipo:"Fundos Imobiliários" },
  { empresa: "CAIXA RIO BRAVO FUNDO DE FUNDOS", ativo: "CXRI11", tipo:"Fundos Imobiliários" },
  { empresa: "CAIXA TRX LOGÍSTICA RENDA", ativo: "CXTL11", tipo:"Fundos Imobiliários" },
  { empresa: "CYRELA REALT ON", ativo: "CYRE3", tipo:"Ações" },
  { empresa: "DIAMANTE", ativo: "DAMT11B", tipo:"Fundos Imobiliários" },
  { empresa: "DASA ON", ativo: "DASA1", tipo:"Ações" },
  { empresa: "DASA ON", ativo: "DASA3", tipo:"Ações" },
  { empresa: "DIRECIONAL ON", ativo: "DIRR3", tipo:"Ações" },
  { empresa: "DEL MONTE AJAX", ativo: "DLMT11", tipo:"Fundos Imobiliários" },
  { empresa: "MAC FII", ativo: "DMAC11", tipo:"Fundos Imobiliários" },
  { empresa: "DOMMO ON", ativo: "DMMO11", tipo:"Ações" },
  { empresa: "DOMMO ON", ativo: "DMMO3", tipo:"Ações" },
  { empresa: "D1000 VAREJO FARMA PARTI... ON", ativo: "DMVF3", tipo:"Ações" },
  { empresa: "DOHLER ON", ativo: "DOHL3", tipo:"Ações" },
  { empresa: "DOHLER PN", ativo: "DOHL4", tipo:"Ações" },
  { empresa: "REAG RENDA IMOBILIÁRIA", ativo: "DOMC11", tipo:"Fundos Imobiliários" },
  { empresa: "DOVEL", ativo: "DOVL11B", tipo:"Fundos Imobiliários" },
  { empresa: "MULTIGESTÃO RENDA COMERCIAL", ativo: "DRIT11B", tipo:"Fundos Imobiliários" },
  { empresa: "DTCOM ON", ativo: "DTCY1", tipo:"Ações" },
  { empresa: "DTCOM ON", ativo: "DTCY3", tipo:"Ações" },
  { empresa: "DTCOM PN", ativo: "DTCY4", tipo:"Ações" },
  { empresa: "DURATEX ON", ativo: "DTEX3", tipo:"Ações" },
  { empresa: "AÇO ALTONA ON", ativo: "EALT3", tipo:"Ações" },
  { empresa: "AÇO ALTONA PN", ativo: "EALT4", tipo:"Ações" },
  { empresa: "ECORODOVIAS ON", ativo: "ECOR3", tipo:"Ações" },
  { empresa: "ENCORPAR ON", ativo: "ECPR3", tipo:"Ações" },
  { empresa: "ENCORPAR PN", ativo: "ECPR4", tipo:"Ações" },
  { empresa: "EDIFÍCIO OURINVEST", ativo: "EDFO11B", tipo:"Fundos Imobiliários" },
  { empresa: "EDIFÍCIO GALERIA", ativo: "EDGA11", tipo:"Fundos Imobiliários" },
  { empresa: "CEEE-GT ON", ativo: "EEEL3", tipo:"Ações" },
  { empresa: "CEEE-GT PN", ativo: "EEEL4", tipo:"Ações" },
  { empresa: "ENGIE BRASIL ON", ativo: "EGIE3", tipo:"Ações" },
  { empresa: "ELEKTRO ON", ativo: "EKTR3", tipo:"Ações" },
  { empresa: "ELEKTRO PN", ativo: "EKTR4", tipo:"Ações" },
  { empresa: "ELDORADO", ativo: "ELDO11B", tipo:"Fundos Imobiliários" },
  { empresa: "ELEKEIROZ ON", ativo: "ELEK11L", tipo:"Ações" },
  { empresa: "ELEKEIROZ PN", ativo: "ELEK12L", tipo:"Ações" },
  { empresa: "ELEKEIROZ ON", ativo: "ELEK3", tipo:"Ações" },
  { empresa: "ELEKEIROZ ON", ativo: "ELEK3L", tipo:"Ações" },
  { empresa: "ELEKEIROZ PN", ativo: "ELEK4", tipo:"Ações" },
  { empresa: "ELEKEIROZ PN", ativo: "ELEK4L", tipo:"Ações" },
  { empresa: "ELETROBRAS ON", ativo: "ELET1", tipo:"Ações" },
  { empresa: "ELETROBRAS PNB", ativo: "ELET11", tipo:"Ações" },
  { empresa: "ELETROBRAS ON", ativo: "ELET3", tipo:"Ações" },
  { empresa: "ELETROBRAS PNA", ativo: "ELET5", tipo:"Ações" },
  { empresa: "ELETROBRAS PNB", ativo: "ELET6", tipo:"Ações" },
  { empresa: "ELETROPAULO ON", ativo: "ELPL3", tipo:"Ações" },
  { empresa: "ELETROPAULO ON", ativo: "ELPL3L", tipo:"Ações" },
  { empresa: "EMAE ON", ativo: "EMAE3", tipo:"Ações" },
  { empresa: "EMAE PN", ativo: "EMAE4", tipo:"Ações" },
  { empresa: "EMBRAER ON", ativo: "EMBR3", tipo:"Ações" },
  { empresa: "ENAUTA ON", ativo: "ENAT3", tipo:"Ações" },
  { empresa: "ENERGIAS BR ON", ativo: "ENBR3", tipo:"Ações" },
  { empresa: "ENEVA ON", ativo: "ENEV3", tipo:"Ações" },
  { empresa: "ENERGISA", ativo: "ENGI12", tipo:"Ações" },
  { empresa: "ENERGISA ON", ativo: "ENGI3", tipo:"Ações" },
  { empresa: "ENERGISA PN", ativo: "ENGI4", tipo:"Ações" },
  { empresa: "CEMAR ON", ativo: "ENMA3B", tipo:"Ações" },
  { empresa: "CEMAR PNA", ativo: "ENMA5B", tipo:"Ações" },
  { empresa: "CEMAR PNB", ativo: "ENMA6B", tipo:"Ações" },
  { empresa: "ENERGISA MT ON", ativo: "ENMT1", tipo:"Ações" },
  { empresa: "ENERGISA MT PN", ativo: "ENMT2", tipo:"Ações" },
  { empresa: "ENERGISA MT ON", ativo: "ENMT3", tipo:"Ações" },
  { empresa: "ENERGISA MT PN", ativo: "ENMT4", tipo:"Ações" },
  { empresa: "CEMAR-CIA ENERGETICA DO ... ON", ativo: "EQMA3B", tipo:"Ações" },
  { empresa: "CEMAR-CIA ENERGETICA DO ... PNA", ativo: "EQMA5B", tipo:"Ações" },
  { empresa: "CEMAR-CIA ENERGETICA DO ... PNB", ativo: "EQMA6B", tipo:"Ações" },
  { empresa: "EQTL PARA ON", ativo: "EQPA3", tipo:"Ações" },
  { empresa: "EQTL PARA PNA", ativo: "EQPA5", tipo:"Ações" },
  { empresa: "EQTL PARA PNB", ativo: "EQPA6", tipo:"Ações" },
  { empresa: "EQTL PARA PNC", ativo: "EQPA7", tipo:"Ações" },
  { empresa: "EQUATORIAL ON", ativo: "EQTL3", tipo:"Ações" },
  { empresa: "EUROPA 105", ativo: "ERPA11", tipo:"Fundos Imobiliários" },
  { empresa: "POLO ESTOQUE II", ativo: "ESTQ11", tipo:"Fundos Imobiliários" },
  { empresa: "ESTRELA ON", ativo: "ESTR3", tipo:"Ações" },
  { empresa: "ESTRELA PN", ativo: "ESTR4", tipo:"Ações" },
  { empresa: "ETERNIT ON", ativo: "ETER1", tipo:"Ações" },
  { empresa: "ETERNIT ON", ativo: "ETER3", tipo:"Ações" },
  { empresa: "ETERNIT ON", ativo: "ETER9", tipo:"Ações" },
  { empresa: "ELETRON ON", ativo: "ETRO3B", tipo:"Ações" },
  { empresa: "EUCATEX ON", ativo: "EUCA3", tipo:"Ações" },
  { empresa: "EUCATEX PN", ativo: "EUCA4", tipo:"Ações" },
  { empresa: "EUROPAR", ativo: "EURO11", tipo:"Fundos Imobiliários" },
  { empresa: "EVEN ON", ativo: "EVEN3", tipo:"Ações" },
  { empresa: "EZTEC ON", ativo: "EZTC3", tipo:"Ações" },
  { empresa: "ANHANGUERA EDUCACIONAL", ativo: "FAED11", tipo:"Fundos Imobiliários" },
  { empresa: "EDIFÍCIO ALMIRANTE BARROSO", ativo: "FAMB11B", tipo:"Fundos Imobiliários" },
  { empresa: "ATHENA I", ativo: "FATN11", tipo:"Fundos Imobiliários" },
  { empresa: "EDIFÍCIO CASTELO", ativo: "FCAS11", tipo:"Fundos Imobiliários" },
  { empresa: "CAMPUS FARIA LIMA", ativo: "FCFL11", tipo:"Fundos Imobiliários" },
  { empresa: "FERBASA ON", ativo: "FESA3", tipo:"Ações" },
  { empresa: "FERBASA PN", ativo: "FESA4", tipo:"Ações" },
  { empresa: "BTG PACTUAL FUNDO DE CRI", ativo: "FEXC11", tipo:"Fundos Imobiliários" },
  { empresa: "FER HERINGER ON", ativo: "FHER3", tipo:"Ações" },
  { empresa: "INVEST BEMGE ON", ativo: "FIGE3", tipo:"Ações" },
  { empresa: "INVEST BEMGE PN", ativo: "FIGE4", tipo:"Ações" },
  { empresa: "GENERAL SHOPPING ATIVO E RENDA", ativo: "FIGS11", tipo:"Fundos Imobiliários" },
  { empresa: "INDUSTRIAL DO BRASIL", ativo: "FIIB11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL RENDA I", ativo: "FIIP11B", tipo:"Fundos Imobiliários" },
  { empresa: "INFRA REAL ESTATE", ativo: "FINF11", tipo:"Fundos Imobiliários" },
  { empresa: "SC 401", ativo: "FISC11", tipo:"Fundos Imobiliários" },
  { empresa: "SÃO DOMINGOS", ativo: "FISD11", tipo:"Fundos Imobiliários" },
  { empresa: "VIDA NOVA", ativo: "FIVN11", tipo:"Fundos Imobiliários" },
  { empresa: "FORJA TAURUS PN", ativo: "FJTA13", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "FJTA15", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "FJTA17", tipo:"Ações" },
  { empresa: "FORJA TAURUS ON", ativo: "FJTA3", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "FJTA4", tipo:"Ações" },
  { empresa: "FARIA LIMA CAPITAL RECEBÍVEIS IMOBILIÁRIOS I", ativo: "FLCR11", tipo:"Fundos Imobiliários" },
  { empresa: "FLEX GESTAO DE RELACIONA... ON", ativo: "FLEX3", tipo:"Ações" },
  { empresa: "CONTINENTAL SQUARE FARIA LIMA", ativo: "FLMA11", tipo:"Fundos Imobiliários" },
  { empresa: "FLORIPA SHOPPING", ativo: "FLRP11", tipo:"Fundos Imobiliários" },
  { empresa: "FLEURY ON", ativo: "FLRY3", tipo:"Ações" },
  { empresa: "FLY ACAI PNA PNA", ativo: "FLYC5L", tipo:"Ações" },
  { empresa: "MEMORIAL OFFICE", ativo: "FMOF11", tipo:"Fundos Imobiliários" },
  { empresa: "FIACAO ALGODAO MOCO SA F... PNB", ativo: "FMSA6L", tipo:"Ações" },
  { empresa: "FRANGO NORTE PNA PNA", ativo: "FNAG5L", tipo:"Ações" },
  { empresa: "BCO FINANSINOS ON", ativo: "FNCN3", tipo:"Ações" },
  { empresa: "HEDGE TOP FOFII 2", ativo: "FOFT11", tipo:"Fundos Imobiliários" },
  { empresa: "PROJETO ÁGUA BRANCA", ativo: "FPAB11", tipo:"Fundos Imobiliários" },
  { empresa: "PEDRA NEGRA RENDA IMOBILIÁRIA", ativo: "FPNG11", tipo:"Fundos Imobiliários" },
  { empresa: "FRAS-LE ON", ativo: "FRAS3", tipo:"Ações" },
  { empresa: "METALFRIO ON", ativo: "FRIO3", tipo:"Ações" },
  { empresa: "RUMO MALHA NORTE ON", ativo: "FRRN3B", tipo:"Ações" },
  { empresa: "RUMO MALHA NORTE PNA", ativo: "FRRN5B", tipo:"Ações" },
  { empresa: "RUMO MALHA NORTE PNB", ativo: "FRRN6B", tipo:"Ações" },
  { empresa: "POMIFRUTAS ON", ativo: "FRTA3", tipo:"Ações" },
  { empresa: "OPPORTUNITY", ativo: "FTCE11B", tipo:"Fundos Imobiliários" },
  { empresa: "TMJ FII", ativo: "FTMJ11", tipo:"Fundos Imobiliários" },
  { empresa: "FUNDO VBI FL 4440", ativo: "FVBI11", tipo:"Fundos Imobiliários" },
  { empresa: "FRUTIVITA PNA", ativo: "FVIT5L", tipo:"Ações" },
  { empresa: "VIA PARQUE", ativo: "FVPQ11", tipo:"Fundos Imobiliários" },
  { empresa: "GALAPAGOS FUNDO DE FUNDOS", ativo: "GCFF11", tipo:"Fundos Imobiliários" },
  { empresa: "GER PARANAP ON", ativo: "GEPA3", tipo:"Ações" },
  { empresa: "GER PARANAP PN", ativo: "GEPA4", tipo:"Ações" },
  { empresa: "GEMASA PNC PNC", ativo: "GESA7L", tipo:"Ações" },
  { empresa: "GENERAL SEVERIANO", ativo: "GESE11", tipo:"Fundos Imobiliários" },
  { empresa: "GAFISA ON", ativo: "GFSA1", tipo:"Ações" },
  { empresa: "GAFISA", ativo: "GFSA11", tipo:"Ações" },
  { empresa: "GAFISA", ativo: "GFSA12", tipo:"Ações" },
  { empresa: "GAFISA ON", ativo: "GFSA3", tipo:"Ações" },
  { empresa: "GAFISA ON", ativo: "GFSA9", tipo:"Ações" },
  { empresa: "GERDAU ON", ativo: "GGBR3", tipo:"Ações" },
  { empresa: "GERDAU PN", ativo: "GGBR4", tipo:"Ações" },
  { empresa: "GGR COVEPI", ativo: "GGRC11", tipo:"Fundos Imobiliários" },
  { empresa: "INTERMEDICA ON", ativo: "GNDI3", tipo:"Ações" },
  { empresa: "GERDAU MET ON", ativo: "GOAU3", tipo:"Ações" },
  { empresa: "GERDAU MET PN", ativo: "GOAU4", tipo:"Ações" },
  { empresa: "GOL PN", ativo: "GOLL11", tipo:"Ações" },
  { empresa: "GOL PN", ativo: "GOLL12", tipo:"Ações" },
  { empresa: "GOL PN", ativo: "GOLL4", tipo:"Ações" },
  { empresa: "CELGPAR ON", ativo: "GPAR1", tipo:"Ações" },
  { empresa: "CELGPAR ON", ativo: "GPAR3", tipo:"Ações" },
  { empresa: "GPC PART ON", ativo: "GPCP3", tipo:"Ações" },
  { empresa: "GPC PART PN", ativo: "GPCP4", tipo:"Ações" },
  { empresa: "GAMELEIRA PNA PNA", ativo: "GPSA5L", tipo:"Ações" },
  { empresa: "CSHG GR LOUVEIRA", ativo: "GRLV11", tipo:"Fundos Imobiliários" },
  { empresa: "GRENDENE ON", ativo: "GRND3", tipo:"Ações" },
  { empresa: "GENERAL SHOPPING E OUTLETS", ativo: "GSFI11", tipo:"Fundos Imobiliários" },
  { empresa: "GENERAL SHOP ON", ativo: "GSHP3", tipo:"Ações" },
  { empresa: "GRUPO SOMA S.A", ativo: "GSOM3", tipo:"Ações" },
  { empresa: "GREEN TOWERS", ativo: "GTWR11", tipo:"Fundos Imobiliários" },
  { empresa: "GUARARAPES ON", ativo: "GUAR3", tipo:"Ações" },
  { empresa: "GWI CONDOMÍNIOS LOGÍSTICOS", ativo: "GWIC11", tipo:"Fundos Imobiliários" },
  { empresa: "HEDGE AAA", ativo: "HAAA11", tipo:"Fundos Imobiliários" },
  { empresa: "HABITAT II", ativo: "HABT11", tipo:"Fundos Imobiliários" },
  { empresa: "HAGA ON", ativo: "HAGA3", tipo:"Ações" },
  { empresa: "HAGA PN", ativo: "HAGA4", tipo:"Ações" },
  { empresa: "HAPVIDA ON", ativo: "HAPV3", tipo:"Ações" },
  { empresa: "HELBOR ON", ativo: "HBOR3", tipo:"Ações" },
  { empresa: "MULTI RENDA URBANA", ativo: "HBRH11", tipo:"Fundos Imobiliários" },
  { empresa: "HABITASUL ON", ativo: "HBTS3", tipo:"Ações" },
  { empresa: "HABITASUL PNA", ativo: "HBTS5", tipo:"Ações" },
  { empresa: "HABITASUL PNB", ativo: "HBTS6", tipo:"Ações" },
  { empresa: "HABITAT I", ativo: "HBTT11", tipo:"Fundos Imobiliários" },
  { empresa: "HOTEL CAICARA PN", ativo: "HCCR4L", tipo:"Ações" },
  { empresa: "HOSPITAL DA CRIANÇA", ativo: "HCRI11", tipo:"Fundos Imobiliários" },
  { empresa: "HECTARE CE", ativo: "HCTR11", tipo:"Fundos Imobiliários" },
  { empresa: "FII HECTARE CI", ativo: "HCTR12", tipo:"Ações" },
  { empresa: "HERCULES ON", ativo: "HETA3", tipo:"Ações" },
  { empresa: "HERCULES PN", ativo: "HETA4", tipo:"Ações" },
  { empresa: "HEDGE TOP FOFII 3", ativo: "HFOF11", tipo:"Fundos Imobiliários" },
  { empresa: "HEDGE BRASIL SHOPPING", ativo: "HGBS11", tipo:"Fundos Imobiliários" },
  { empresa: "CSHG RECEBÍVEIS IMOBILIÁRIOS", ativo: "HGCR11", tipo:"Fundos Imobiliários" },
  { empresa: "FII CSHG CRI CI", ativo: "HGCR12", tipo:"Ações" },
  { empresa: "CSHG IMOBILIÁRIO FOF", ativo: "HGFF11", tipo:"Fundos Imobiliários" },
  { empresa: "CSHG LOGÍSTICA", ativo: "HGLG11", tipo:"Fundos Imobiliários" },
  { empresa: "CSHG PRIME OFFICES", ativo: "HGPO11", tipo:"Fundos Imobiliários" },
  { empresa: "CSHG REAL ESTATE", ativo: "HGRE11", tipo:"Fundos Imobiliários" },
  { empresa: "CSHG RENDA URBANA", ativo: "HGRU11", tipo:"Fundos Imobiliários" },
  { empresa: "CIA HERING ON", ativo: "HGTX3", tipo:"Ações" },
  { empresa: "HEDGE LOGÍSTICA", ativo: "HLOG11", tipo:"Fundos Imobiliários" },
  { empresa: "HEDGE SHOPPING PRAÇA DA MOÇA", ativo: "HMOC11", tipo:"Fundos Imobiliários" },
  { empresa: "HOTEIS OTHON ON", ativo: "HOOT3", tipo:"Ações" },
  { empresa: "HOTEIS OTHON PN", ativo: "HOOT4", tipo:"Ações" },
  { empresa: "HOUSI", ativo: "HOSI11", tipo:"Fundos Imobiliários" },
  { empresa: "HEDGE SHOPPING PARQUE DOM PEDRO", ativo: "HPDP11", tipo:"Fundos Imobiliários" },
  { empresa: "HEDGE REALTY DEVELOPMENT", ativo: "HRDF11", tipo:"Fundos Imobiliários" },
  { empresa: "HEDGE RECEBÍVEIS IMOBILIÁRIOS", ativo: "HREC11", tipo:"Fundos Imobiliários" },
  { empresa: "HSI ATIVOS FINANCEIROS", ativo: "HSAF11", tipo:"Fundos Imobiliários" },
  { empresa: "HSI MALLS", ativo: "HSML11", tipo:"Fundos Imobiliários" },
  { empresa: "FII HSI MALLCI", ativo: "HSML12", tipo:"Ações" },
  { empresa: "HSI RENDA IMOBILIÁRIA", ativo: "HSRE11", tipo:"Fundos Imobiliários" },
  { empresa: "HOTEL MAXINVEST", ativo: "HTMX11", tipo:"Fundos Imobiliários" },
  { empresa: "HOSPITAL UNIMED SUL CAPIXABA", ativo: "HUSC11", tipo:"Fundos Imobiliários" },
  { empresa: "HUSI", ativo: "HUSI11", tipo:"Fundos Imobiliários" },
  { empresa: "HYPERA ON", ativo: "HYPE3", tipo:"Ações" },
  { empresa: "FOF INTEGRAL BREI", ativo: "IBFF11", tipo:"Fundos Imobiliários" },
  { empresa: "ISHARES CARBON EFFICIENT", ativo: "ICO211", tipo:"Ações" },
  { empresa: "INDUSVAL ON", ativo: "IDVL3", tipo:"Ações" },
  { empresa: "INDUSVAL PN", ativo: "IDVL4", tipo:"Ações" },
  { empresa: "IFI-E", ativo: "IFIE11", tipo:"Fundos Imobiliários" },
  { empresa: "IFIX ÍNDICE DE FUNDOS IMOBILIÁRIOS", ativo: "IFIX", tipo:"Fundos Imobiliários" },
  { empresa: "IRRIGACAO SANTO ANDRE SA... PNA", ativo: "IGSA5L", tipo:"Ações" },
  { empresa: "INEPAR ON", ativo: "INEP3", tipo:"Ações" },
  { empresa: "INEPAR PN", ativo: "INEP4", tipo:"Ações" },
  { empresa: "INGA AGROFLORESTAL PN", ativo: "INGA4L", tipo:"Ações" },
  { empresa: "INTER CONSTRUTORA ON", ativo: "INNT3", tipo:"Ações" },
  { empresa: "IRB BRASIL ON", ativo: "IRBR1", tipo:"Ações" },
  { empresa: "IRB BRASIL ON", ativo: "IRBR3", tipo:"Ações" },
  { empresa: "BRASIL RESSEGUROS", ativo: "IRBR9", tipo:"Ações" },
  { empresa: "IRIDIUM RECEBÍVEIS IMOBILIÁRIOS", ativo: "IRDM11", tipo:"Fundos Imobiliários" },
  { empresa: "ISE INDICE SUSTENTABILID...", ativo: "ISEE11", tipo:"Ações" },
  { empresa: "ITAUSA ON", ativo: "ITSA3", tipo:"Ações" },
  { empresa: "ITAUSA PN", ativo: "ITSA4", tipo:"Ações" },
  { empresa: "ITAU UNIBANCO ON", ativo: "ITUB3", tipo:"Ações" },
  { empresa: "ITAU UNIBANCO PN", ativo: "ITUB4", tipo:"Ações" },
  { empresa: "INVESTS PARTICIPACOES IN... ON", ativo: "IVPR3B", tipo:"Ações" },
  { empresa: "INVESTS PARTICIPACOES IN... PN", ativo: "IVPR4B", tipo:"Ações" },
  { empresa: "JAHYR SEIXAS GONCALVES A... PNA", ativo: "JAHY5L", tipo:"Ações" },
  { empresa: "J B DUARTE ON", ativo: "JBDU3", tipo:"Ações" },
  { empresa: "J B DUARTE PN", ativo: "JBDU4", tipo:"Ações" },
  { empresa: "JBS ON", ativo: "JBSS3", tipo:"Ações" },
  { empresa: "JOAO FORTES ON", ativo: "JFEN3", tipo:"Ações" },
  { empresa: "JHSF PART ON", ativo: "JHSF3", tipo:"Ações" },
  { empresa: "JOSAPAR ON", ativo: "JOPA3", tipo:"Ações" },
  { empresa: "JOSAPAR PN", ativo: "JOPA4", tipo:"Ações" },
  { empresa: "JPP ALLOCATON MOGNO", ativo: "JPPA11", tipo:"Fundos Imobiliários" },
  { empresa: "JPP CAPITAL", ativo: "JPPC11", tipo:"Fundos Imobiliários" },
  { empresa: "JEREISSATI ON", ativo: "JPSA3", tipo:"Ações" },
  { empresa: "SHOPPING JARDIM SUL", ativo: "JRDM11", tipo:"Fundos Imobiliários" },
  { empresa: "JS REAL ESTATE RENDA IMOBILIÁRIA", ativo: "JSIM11", tipo:"Fundos Imobiliários" },
  { empresa: "JSL ON", ativo: "JSLG3", tipo:"Ações" },
  { empresa: "JS REAL ESTATE MULTIGESTÃO", ativo: "JSRE11", tipo:"Fundos Imobiliários" },
  { empresa: "JT PREV DESENVOLVIMENTO HABITACIONAL", ativo: "JTPR11", tipo:"Fundos Imobiliários" },
  { empresa: "KEPLER WEBER", ativo: "KEPL11", tipo:"Ações" },
  { empresa: "KEPLER WEBER ON", ativo: "KEPL3", tipo:"Ações" },
  { empresa: "KINEA FUNDO DE FUNDOS", ativo: "KFOF11", tipo:"Fundos Imobiliários" },
  { empresa: "EVEN PERMUTA KINEA", ativo: "KINP11", tipo:"Fundos Imobiliários" },
  { empresa: "KLABIN ON", ativo: "KLBN3", tipo:"Ações" },
  { empresa: "KLABIN PN", ativo: "KLBN4", tipo:"Ações" },
  { empresa: "KINEA RENDIMENTOS IMOBILIÁRIOS FII", ativo: "KNCR11", tipo:"Fundos Imobiliários" },
  { empresa: "KINEA HIGH YIELD CRI", ativo: "KNHY11", tipo:"Fundos Imobiliários" },
  { empresa: "KINEA ÍNDICES DE PREÇOS", ativo: "KNIP11", tipo:"Fundos Imobiliários" },
  { empresa: "KINEA II REAL ESTATE EQUITY", ativo: "KNRE11", tipo:"Fundos Imobiliários" },
  { empresa: "KINEA RENDA IMOBILIÁRIA", ativo: "KNRI11", tipo:"Fundos Imobiliários" },
  { empresa: "LOJAS AMERIC ON", ativo: "LAME1", tipo:"Ações" },
  { empresa: "LOJAS AMERIC PN", ativo: "LAME10", tipo:"Ações" },
  { empresa: "LOJAS AMERIC PN", ativo: "LAME2", tipo:"Ações" },
  { empresa: "LOJAS AMERICANAS ON", ativo: "LAME3", tipo:"Ações" },
  { empresa: "LOJAS AMERICANAS PN", ativo: "LAME4", tipo:"Ações" },
  { empresa: "LOJAS AMERIC ON", ativo: "LAME9", tipo:"Ações" },
  { empresa: "LEGATUS SHOPPINGS", ativo: "LASC11", tipo:"Fundos Imobiliários" },
  { empresa: "LATERES", ativo: "LATR11B", tipo:"Fundos Imobiliários" },
  { empresa: "LOCAMERICA ON", ativo: "LCAM3", tipo:"Ações" },
  { empresa: "METAL LEVE ON", ativo: "LEVE3", tipo:"Ações" },
  { empresa: "LOFT II", ativo: "LFTT11", tipo:"Fundos Imobiliários" },
  { empresa: "LOG CP INTER", ativo: "LGCP11", tipo:"Fundos Imobiliários" },
  { empresa: "LIGHT ON", ativo: "LIGT3", tipo:"Ações" },
  { empresa: "LINX ON", ativo: "LINX3", tipo:"Ações" },
  { empresa: "ELETROPAR ON", ativo: "LIPR3", tipo:"Ações" },
  { empresa: "LIQ ON", ativo: "LIQO1", tipo:"Ações" },
  { empresa: "LIQ ON", ativo: "LIQO3", tipo:"Ações" },
  { empresa: "LOJAS QUERO-QUERO ON", ativo: "LJQQ3", tipo:"Ações" },
  { empresa: "LE LIS BLANC ON", ativo: "LLIS3", tipo:"Ações" },
  { empresa: "LIFEMED ON", ativo: "LMED3", tipo:"Ações" },
  { empresa: "LOFT I (COTA SÊNIOR)", ativo: "LOFT11B", tipo:"Fundos Imobiliários" },
  { empresa: "LOFT I (COTA SUBORDINADA)", ativo: "LOFT13B", tipo:"Fundos Imobiliários" },
  { empresa: "LOG COMMERCIAL ON", ativo: "LOGG3", tipo:"Ações" },
  { empresa: "LOG IN ON", ativo: "LOGN3", tipo:"Ações" },
  { empresa: "LOPES BRASIL ON", ativo: "LPSB3", tipo:"Ações" },
  { empresa: "LOJAS RENNER ON", ativo: "LREN3", tipo:"Ações" },
  { empresa: "LITEL PARTICIPACOES ON", ativo: "LTEL3B", tipo:"Ações" },
  { empresa: "LITEL PNA", ativo: "LTEL5B", tipo:"Ações" },
  { empresa: "LITELA PARTICIPACOES ON", ativo: "LTLA3B", tipo:"Ações" },
  { empresa: "LUGGO", ativo: "LUGG11", tipo:"Fundos Imobiliários" },
  { empresa: "LUPATECH ON", ativo: "LUPA11", tipo:"Ações" },
  { empresa: "LUPATECH ON", ativo: "LUPA3", tipo:"Ações" },
  { empresa: "TREVISA ON", ativo: "LUXM3", tipo:"Ações" },
  { empresa: "TREVISA PN", ativo: "LUXM4", tipo:"Ações" },
  { empresa: "VBI LOGÍSTICO", ativo: "LVBI11", tipo:"Fundos Imobiliários" },
  { empresa: "LOCAWEB ON", ativo: "LWSA3", tipo:"Ações" },
  { empresa: "MALLS BRASIL PLURAL", ativo: "MALL11", tipo:"Fundos Imobiliários" },
  { empresa: "CEMPE ON", ativo: "MAPT3", tipo:"Ações" },
  { empresa: "CEMPE PN", ativo: "MAPT4", tipo:"Ações" },
  { empresa: "MAX RETAIL", ativo: "MAXR11", tipo:"Fundos Imobiliários" },
  { empresa: "MAXVINIL PNB PNB", ativo: "MAXV6L", tipo:"Ações" },
  { empresa: "MAXVINIL PNB PNC", ativo: "MAXV7L", tipo:"Ações" },
  { empresa: "MERCANTIL DO BRASIL", ativo: "MBRF11", tipo:"Fundos Imobiliários" },
  { empresa: "MAUÁ CAPITAL RECEBÍVEIS IMOBILIÁRIOS", ativo: "MCCI11", tipo:"Fundos Imobiliários" },
  { empresa: "CEPAC MCRJ CPA MB", ativo: "MCRJ11B", tipo:"Ações" },
  { empresa: "M.DIAS BRANCO ON", ativo: "MDIA3", tipo:"Ações" },
  { empresa: "MOURA DUBEAUX ON", ativo: "MDNE3", tipo:"Ações" },
  { empresa: "IMC S/A ON", ativo: "MEAL3", tipo:"Ações" },
  { empresa: "MENDES JR ON", ativo: "MEND3", tipo:"Ações" },
  { empresa: "MENDES JR PNA", ativo: "MEND5", tipo:"Ações" },
  { empresa: "MENDES JR PNB", ativo: "MEND6", tipo:"Ações" },
  { empresa: "MERCANTIL DO BRASIL ON", ativo: "MERC3", tipo:"Ações" },
  { empresa: "MERCANTIL DO BRASIL PN", ativo: "MERC4", tipo:"Ações" },
  { empresa: "MÉRITO FUNDOS E AÇÕES IMOBILIÁRIAS", ativo: "MFAI11", tipo:"Fundos Imobiliários" },
  { empresa: "MÉRITO DESENVOLVIMENTO IMOBILIÁRIO I", ativo: "MFII11", tipo:"Fundos Imobiliários" },
  { empresa: "MANGELS ON", ativo: "MGEL3", tipo:"Ações" },
  { empresa: "MANGELS PN", ativo: "MGEL4", tipo:"Ações" },
  { empresa: "MOGNO FUNDO DE FUNDOS", ativo: "MGFF11", tipo:"Fundos Imobiliários" },
  { empresa: "FII MONGNO CI", ativo: "MGFF12", tipo:"Ações" },
  { empresa: "MOGNO HOTEIS", ativo: "MGHT11", tipo:"Fundos Imobiliários" },
  { empresa: "MAGAZINE LUIZA ON", ativo: "MGLU3", tipo:"Ações" },
  { empresa: "MILLS ON", ativo: "MILS3", tipo:"Ações" },
  { empresa: "MINT EDUCACIONAL", ativo: "MINT11", tipo:"Fundos Imobiliários" },
  { empresa: "MIDLARGE CAP", ativo: "MLCX11", tipo:"Ações" },
  { empresa: "MINASMAQUINAS ON", ativo: "MMAQ3", tipo:"Ações" },
  { empresa: "MINASMAQUINAS PN", ativo: "MMAQ4", tipo:"Ações" },
  { empresa: "MMX MINER", ativo: "MMXM11", tipo:"Ações" },
  { empresa: "MMX MINER ON", ativo: "MMXM3", tipo:"Ações" },
  { empresa: "MUNDIAL ON", ativo: "MNDL3", tipo:"Ações" },
  { empresa: "MINUPAR ON", ativo: "MNPR3", tipo:"Ações" },
  { empresa: "TERMINAL GARAGEM MENEZES... ON", ativo: "MNZC3B", tipo:"Ações" },
  { empresa: "MONT ARANHA ON", ativo: "MOAR3", tipo:"Ações" },
  { empresa: "MULTIOFFICES 2", ativo: "MOFF11", tipo:"Fundos Imobiliários" },
  { empresa: "MORE REAL ESTATE FOF", ativo: "MORE11", tipo:"Fundos Imobiliários" },
  { empresa: "MOVIDA ON", ativo: "MOVI3", tipo:"Ações" },
  { empresa: "MARFRIG ON", ativo: "MRFG3", tipo:"Ações" },
  { empresa: "MRS LOGISTICA ON", ativo: "MRSA3B", tipo:"Ações" },
  { empresa: "MRS LOGISTICA PNA", ativo: "MRSA5B", tipo:"Ações" },
  { empresa: "MRS LOGISTICA PNB", ativo: "MRSA6B", tipo:"Ações" },
  { empresa: "MRV ON", ativo: "MRVE3", tipo:"Ações" },
  { empresa: "MAIS SHOPPING LARGO 13", ativo: "MSHP11", tipo:"Fundos Imobiliários" },
  { empresa: "MELHOR SP ON", ativo: "MSPA3", tipo:"Ações" },
  { empresa: "MELHOR SP PN", ativo: "MSPA4", tipo:"Ações" },
  { empresa: "MAESTRO LOCADORA ON", ativo: "MSRO3", tipo:"Ações" },
  { empresa: "METAL IGUAÇU ON", ativo: "MTIG3", tipo:"Ações" },
  { empresa: "METAL IGUAÇU PN", ativo: "MTIG4", tipo:"Ações" },
  { empresa: "MULTIOFFICES 1", ativo: "MTOF11", tipo:"Fundos Imobiliários" },
  { empresa: "MITRE REALTY EMPREENDIMENTOS E PARTICIPACOES LTDA", ativo: "MTRE", tipo:"Ações" },
  { empresa: "MITRE REALTY ON", ativo: "MTRE3", tipo:"Ações" },
  { empresa: "METROPOLIS", ativo: "MTRS11", tipo:"Fundos Imobiliários" },
  { empresa: "METISA ON", ativo: "MTSA3", tipo:"Ações" },
  { empresa: "METISA PN", ativo: "MTSA4", tipo:"Ações" },
  { empresa: "MULTIPLAN ON", ativo: "MULT3", tipo:"Ações" },
  { empresa: "MV9 FII", ativo: "MVFI11", tipo:"Fundos Imobiliários" },
  { empresa: "WETZEL ON", ativo: "MWET3", tipo:"Ações" },
  { empresa: "WETZEL PN", ativo: "MWET4", tipo:"Ações" },
  { empresa: "MAXI RENDA", ativo: "MXRF11", tipo:"Fundos Imobiliários" },
  { empresa: "FII MAXI REN", ativo: "MXRF12", tipo:"Ações" },
  { empresa: "IOCHP-MAXION ON", ativo: "MYPK3", tipo:"Ações" },
  { empresa: "NADIR FIGUEI ON", ativo: "NAFG11L", tipo:"Ações" },
  { empresa: "NADIR FIGUEI PN", ativo: "NAFG12L", tipo:"Ações" },
  { empresa: "NADIR FIGUEIREDO ON", ativo: "NAFG3", tipo:"Ações" },
  { empresa: "NADIR FIGUEI ON", ativo: "NAFG3L", tipo:"Ações" },
  { empresa: "NADIR FIGUEIREDO PN", ativo: "NAFG4", tipo:"Ações" },
  { empresa: "NADIR FIGUEI PN", ativo: "NAFG4L", tipo:"Ações" },
  { empresa: "NCH BRASIL RECEBÍVEIS IMOBILIÁRIOS", ativo: "NCHB11", tipo:"Fundos Imobiliários" },
  { empresa: "SUZANO HOLD ON", ativo: "NEMO3", tipo:"Ações" },
  { empresa: "SUZANO HOLD PNA", ativo: "NEMO5", tipo:"Ações" },
  { empresa: "SUZANO HOLD PNB", ativo: "NEMO6", tipo:"Ações" },
  { empresa: "NEOENERGIA ON", ativo: "NEOE3", tipo:"Ações" },
  { empresa: "NEWPORT LOGÍSTICA", ativo: "NEWL11", tipo:"Fundos Imobiliários" },
  { empresa: "NEWPORT RENDA URBANA", ativo: "NEWU11", tipo:"Fundos Imobiliários" },
  { empresa: "NORDON MET ON", ativo: "NORD3", tipo:"Ações" },
  { empresa: "NESTPAR", ativo: "NPAR11", tipo:"Fundos Imobiliários" },
  { empresa: "NORTEC QUIMICA ON", ativo: "NRTQ3", tipo:"Ações" },
  { empresa: "HOSPITAL NOSSA SENHORA DE LOURDES", ativo: "NSLU11", tipo:"Fundos Imobiliários" },
  { empresa: "NATURA ON", ativo: "NTCO1", tipo:"Ações" },
  { empresa: "NATURA ON", ativo: "NTCO3", tipo:"Ações" },
  { empresa: "NATURA ON", ativo: "NTCO9", tipo:"Ações" },
  { empresa: "NATURA ON", ativo: "NTCO9L", tipo:"Ações" },
  { empresa: "NUTRIPLANT ON", ativo: "NUTR3", tipo:"Ações" },
  { empresa: "NOVO HORIZONTE", ativo: "NVHO11", tipo:"Fundos Imobiliários" },
  { empresa: "NOVA I", ativo: "NVIF11B", tipo:"Fundos Imobiliários" },
  { empresa: "ODERICH ON", ativo: "ODER3", tipo:"Ações" },
  { empresa: "ODERICH PN", ativo: "ODER4", tipo:"Ações" },
  { empresa: "ODONTOPREV ON", ativo: "ODPV3", tipo:"Ações" },
  { empresa: "OUROFINO S/A ON", ativo: "OFSA3", tipo:"Ações" },
  { empresa: "OI ON", ativo: "OIBR3", tipo:"Ações" },
  { empresa: "OI PN", ativo: "OIBR4", tipo:"Ações" },
  { empresa: "OMEGA GER ON", ativo: "OMGE3", tipo:"Ações" },
  { empresa: "THE ONE", ativo: "ONEF11", tipo:"Fundos Imobiliários" },
  { empresa: "GAMA PARTICIPACOES ON", ativo: "OPGM3B", tipo:"Ações" },
  { empresa: "OPPORTUNITY ENERGIA PART... ON", ativo: "OPHE3B", tipo:"Ações" },
  { empresa: "SUDESTE ON", ativo: "OPSE3B", tipo:"Ações" },
  { empresa: "SUL 116 PARTICIPACOES ON", ativo: "OPTS3B", tipo:"Ações" },
  { empresa: "OURO VERDE DESENVOLVIMENTO IMOBILIÁRIO", ativo: "ORPD11", tipo:"Fundos Imobiliários" },
  { empresa: "OSX BRASIL ON", ativo: "OSXB3", tipo:"Ações" },
  { empresa: "OURINVEST CYRELA", ativo: "OUCY11", tipo:"Fundos Imobiliários" },
  { empresa: "OURINVEST FUNDO DE FUNDOS", ativo: "OUFF11", tipo:"Fundos Imobiliários" },
  { empresa: "FD DE INV IMOBLIARIO OUR...", ativo: "OUFF12", tipo:"Ações" },
  { empresa: "OURINVEST JPP", ativo: "OUJP11", tipo:"Fundos Imobiliários" },
  { empresa: "OURINVEST LOGÍSTICA", ativo: "OULG11", tipo:"Fundos Imobiliários" },
  { empresa: "E OULG11 B", ativo: "OULG12B", tipo:"Ações" },
  { empresa: "PANAMBY", ativo: "PABY11", tipo:"Fundos Imobiliários" },
  { empresa: "IHPARDINI ON", ativo: "PARD3", tipo:"Ações" },
  { empresa: "PATEO BANDEIRANTES", ativo: "PATB11", tipo:"Fundos Imobiliários" },
  { empresa: "PÁTRIA EDIFÍCIOS CORPORATIVOS", ativo: "PATC11", tipo:"Fundos Imobiliários" },
  { empresa: "PANATLANTICA PN", ativo: "PATI10", tipo:"Ações" },
  { empresa: "PANATLANTICA PN", ativo: "PATI10L", tipo:"Ações" },
  { empresa: "PANATLANTICA ON", ativo: "PATI3", tipo:"Ações" },
  { empresa: "PANATLANTICA PN", ativo: "PATI4", tipo:"Ações" },
  { empresa: "PANATLANTICA ON", ativo: "PATI9", tipo:"Ações" },
  { empresa: "PANATLANTICA ON", ativo: "PATI9L", tipo:"Ações" },
  { empresa: "PÁTRIA LOGÍSTICA", ativo: "PATL11", tipo:"Fundos Imobiliários" },
  { empresa: "PROLOGIS BRAZIL LOGISTICS VENTURE", ativo: "PBLV11", tipo:"Fundos Imobiliários" },
  { empresa: "PANAMBY RENDA MASTER", ativo: "PBYR11", tipo:"Fundos Imobiliários" },
  { empresa: "PÃO DE AÇUCAR ON", ativo: "PCAR3", tipo:"Ações" },
  { empresa: "P.ACUCAR-CBD PN", ativo: "PCAR4", tipo:"Ações" },
  { empresa: "PEDRA GRANDEPNA PNA", ativo: "PDGD5L", tipo:"Ações" },
  { empresa: "PDG REALT ON", ativo: "PDGR3", tipo:"Ações" },
  { empresa: "PADTEC ON", ativo: "PDTC", tipo:"Ações" },
  { empresa: "PADTEC ON", ativo: "PDTC3", tipo:"Ações" },
  { empresa: "PAR AL BAHIA ON", ativo: "PEAB3", tipo:"Ações" },
  { empresa: "PAR AL BAHIA PN", ativo: "PEAB4", tipo:"Ações" },
  { empresa: "PETROBRAS ON", ativo: "PETR3", tipo:"Ações" },
  { empresa: "PETROBRAS PN", ativo: "PETR4", tipo:"Ações" },
  { empresa: "PROFARMA ON", ativo: "PFRM3", tipo:"Ações" },
  { empresa: "PINE ON", ativo: "PINE1", tipo:"Ações" },
  { empresa: "PINE PN", ativo: "PINE10", tipo:"Ações" },
  { empresa: "PINE PN", ativo: "PINE2", tipo:"Ações" },
  { empresa: "PINE ON", ativo: "PINE3", tipo:"Ações" },
  { empresa: "PINE PN", ativo: "PINE4", tipo:"Ações" },
  { empresa: "PINE ON", ativo: "PINE9", tipo:"Ações" },
  { empresa: "PLASCAR PART ON", ativo: "PLAS11", tipo:"Ações" },
  { empresa: "PLASCAR PART ON", ativo: "PLAS3", tipo:"Ações" },
  { empresa: "PLURAL RECEBÍVEIS IMOBILIÁRIOS", ativo: "PLCR11", tipo:"Fundos Imobiliários" },
  { empresa: "POLO", ativo: "PLRI11", tipo:"Fundos Imobiliários" },
  { empresa: "PARANAPANEMA ON", ativo: "PMAM3", tipo:"Ações" },
  { empresa: "PREFEITURA MUNICIPAL SAO...", ativo: "PMSP11B", tipo:"Ações" },
  { empresa: "PREFEITURA MUNICIPAL SAO...", ativo: "PMSP12B", tipo:"Ações" },
  { empresa: "CEPAC - PMSP", ativo: "PMSP12BL", tipo:"Ações" },
  { empresa: "PREFEITURA MUNICIPAL SAO...", ativo: "PMSP13B", tipo:"Ações" },
  { empresa: "PINGUS PNA", ativo: "PNGU5L", tipo:"Ações" },
  { empresa: "DIMED ON", ativo: "PNVL3", tipo:"Ações" },
  { empresa: "DIMED PN", ativo: "PNVL4", tipo:"Ações" },
  { empresa: "MARCOPOLO ON", ativo: "POMO3", tipo:"Ações" },
  { empresa: "MARCOPOLO PN", ativo: "POMO4", tipo:"Ações" },
  { empresa: "POLO CRI II", ativo: "PORD11", tipo:"Fundos Imobiliários" },
  { empresa: "FII POLO CRI CI", ativo: "PORD12", tipo:"Ações" },
  { empresa: "POSITIVO TEC ON", ativo: "POSI3", tipo:"Ações" },
  { empresa: "POLPAR ON", ativo: "PPAR3", tipo:"Ações" },
  { empresa: "PAULISTA PRAIA HOTEL PNA", ativo: "PPHT5L", tipo:"Ações" },
  { empresa: "PARQUE ANHANGUERA", ativo: "PQAG11", tipo:"Fundos Imobiliários" },
  { empresa: "PARQUE DOM PEDRO SHOPPING CENTER", ativo: "PQDP11", tipo:"Fundos Imobiliários" },
  { empresa: "PETRORIO ON", ativo: "PRIO3", tipo:"Ações" },
  { empresa: "PRODUTORES ENERGETICOS M... ON", ativo: "PRMN3B", tipo:"Ações" },
  { empresa: "PRINER ON", ativo: "PRNR3", tipo:"Ações" },
  { empresa: "PROMPT PARTICIPACOES ON", ativo: "PRPT3B", tipo:"Ações" },
  { empresa: "PERSONALE I", ativo: "PRSN11B", tipo:"Fundos Imobiliários" },
  { empresa: "PRESIDENTE VARGAS", ativo: "PRSV11", tipo:"Fundos Imobiliários" },
  { empresa: "MULTI PROPERTIES", ativo: "PRTS11", tipo:"Fundos Imobiliários" },
  { empresa: "SAUIPE SA (EX PARSEG PAR... ON", ativo: "PSEG3", tipo:"Ações" },
  { empresa: "SAUIPE SA (EX PARSEG PAR... PN", ativo: "PSEG4", tipo:"Ações" },
  { empresa: "PORTO SEGURO ON", ativo: "PSSA3", tipo:"Ações" },
  { empresa: "PORTO SUDESTE", ativo: "PSVM11", tipo:"Ações" },
  { empresa: "PORTOBELLO ON", ativo: "PTBL3", tipo:"Ações" },
  { empresa: "PRATICA PNR M2 PN", ativo: "PTCA11", tipo:"Ações" },
  { empresa: "PRATICA PNR M2 ON", ativo: "PTCA3", tipo:"Ações" },
  { empresa: "PETTENATI ON", ativo: "PTNT3", tipo:"Ações" },
  { empresa: "PETTENATI PN", ativo: "PTNT4", tipo:"Ações" },
  { empresa: "VBI PRIME PROPERTIES", ativo: "PVBI11", tipo:"Fundos Imobiliários" },
  { empresa: "QUASAR AGRO", ativo: "QAGR11", tipo:"Fundos Imobiliários" },
  { empresa: "QUATÁ MONETAI FUNDO DE FUNDOS", ativo: "QMFF11", tipo:"Fundos Imobiliários" },
  { empresa: "QUASAR CRÉDITO IMOBILIÁRIO", ativo: "QREC11", tipo:"Fundos Imobiliários" },
  { empresa: "QUALICORP ON", ativo: "QUAL3", tipo:"Ações" },
  { empresa: "QUALITY SOFTWARE ON", ativo: "QUSW3", tipo:"Ações" },
  { empresa: "524 PARTICIPACOES ON", ativo: "QVQP3B", tipo:"Ações" },
  { empresa: "RAIA DROGASIL ON", ativo: "RADL3", tipo:"Ações" },
  { empresa: "RUMO S.A ON", ativo: "RAIL3", tipo:"Ações" },
  { empresa: "CELULOSE IRANI ON", ativo: "RANI3", tipo:"Ações" },
  { empresa: "CELULOSE IRANI PN", ativo: "RANI4", tipo:"Ações" },
  { empresa: "RANDON PART ON", ativo: "RAPT3", tipo:"Ações" },
  { empresa: "RANDON PART PN", ativo: "RAPT4", tipo:"Ações" },
  { empresa: "RB CAPITAL AGRE", ativo: "RBAG11", tipo:"Fundos Imobiliários" },
  { empresa: "JHSF RIO BRAVO FAZENDA BOA VISTA", ativo: "RBBV11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO CRÉDITO IMOBILIÁRIO I", ativo: "RBCB11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL OFFICE INCOME", ativo: "RBCO11", tipo:"Fundos Imobiliários" },
  { empresa: "FII R INCOMEDM BRAZIL ST...", ativo: "RBCO12", tipo:"Ações" },
  { empresa: "RB CAPITAL DESENVOLVIMENTO RESIDENCIAL II", ativo: "RBDS11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO RENDA EDUCACIONAL", ativo: "RBED11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO IFIX", ativo: "RBFF11", tipo:"Fundos Imobiliários" },
  { empresa: "FII RB CAPITAL DESENVOLV...", ativo: "RBFF12", tipo:"Ações" },
  { empresa: "RB CAPITAL GENERAL SHOPPING SULACAP", ativo: "RBGS11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL DESENVOLVIMENTO RESIDENCIAL IV", ativo: "RBIR11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO CRÉDITO IMOBILIÁRIO IV", ativo: "RBIV11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL PRIME REALTY II", ativo: "RBPD11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL PRIME REALTY I", ativo: "RBPR11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL RENDA II", ativo: "RBRD11", tipo:"Fundos Imobiliários" },
  { empresa: "RBR ALPHA MULTIESTRATÉGIA REAL ESTATE", ativo: "RBRF11", tipo:"Fundos Imobiliários" },
  { empresa: "FII RBRALPHACI", ativo: "RBRF12", tipo:"Ações" },
  { empresa: "RBR LOG", ativo: "RBRL11", tipo:"Fundos Imobiliários" },
  { empresa: "RBR DESENVOLVIMENTO", ativo: "RBRM11", tipo:"Fundos Imobiliários" },
  { empresa: "RBR PROPERTIES FII", ativo: "RBRP11", tipo:"Fundos Imobiliários" },
  { empresa: "FII RBR PROPCI", ativo: "RBRP12", tipo:"Ações" },
  { empresa: "RBR RENDIMENTOS HIGH GRADE", ativo: "RBRR11", tipo:"Fundos Imobiliários" },
  { empresa: "RBR CRÉDITO IMOBILIÁRIO HIGH YIELD", ativo: "RBRY11", tipo:"Fundos Imobiliários" },
  { empresa: "RBR PRIVATE CR", ativo: "RBRY13", tipo:"Ações" },
  { empresa: "RB CAPITAL TFO SITUS", ativo: "RBTS11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO RENDA VAREJO", ativo: "RBVA11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO CRÉDITO IMOBILIÁRIO II", ativo: "RBVO11", tipo:"Fundos Imobiliários" },
  { empresa: "REP 1 CCS", ativo: "RCCS11", tipo:"Fundos Imobiliários" },
  { empresa: "GRUPO RCFA", ativo: "RCFA11", tipo:"Fundos Imobiliários" },
  { empresa: "RBR DESENVOLVIMENTO COMERCIAL FEEDER FOF", ativo: "RCFF11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO BRAVO RENDA CORPORATIVA", ativo: "RCRB11", tipo:"Fundos Imobiliários" },
  { empresa: "RB CAPITAL RENDIMENTOS", ativo: "RCRI11", tipo:"Fundos Imobiliários" },
  { empresa: "RECRUSUL ON", ativo: "RCSL3", tipo:"Ações" },
  { empresa: "RECRUSUL PN", ativo: "RCSL4", tipo:"Ações" },
  { empresa: "ROCHA SANTOS AGROIND PNB", ativo: "RCST6L", tipo:"Ações" },
  { empresa: "RIO CARTADO PNB", ativo: "RCTA6L", tipo:"Ações" },
  { empresa: "RNI ON", ativo: "RDNI3", tipo:"Ações" },
  { empresa: "FUNDO BB RENDA DE PAPÉIS II", ativo: "RDPD11", tipo:"Fundos Imobiliários" },
  { empresa: "UBS BR OFFICE", ativo: "RECT11", tipo:"Fundos Imobiliários" },
  { empresa: "FDO INV IMOB FII UBS BR ...", ativo: "RECT12", tipo:"Ações" },
  { empresa: "REDE ENERGIA ON", ativo: "REDE1", tipo:"Ações" },
  { empresa: "REDE ENERGIA ON", ativo: "REDE3", tipo:"Ações" },
  { empresa: "SOCOPA FII", ativo: "REIT11", tipo:"Fundos Imobiliários" },
  { empresa: "REC LOGÍSTICA", ativo: "RELG11", tipo:"Fundos Imobiliários" },
  { empresa: "LOCALIZA ON", ativo: "RENT3", tipo:"Ações" },
  { empresa: "RB CAPITAL I FUNDO DE FUNDOS", ativo: "RFOF11", tipo:"Fundos Imobiliários" },
  { empresa: "RIOPEC PNC PNB", ativo: "RIPC6L", tipo:"Ações" },
  { empresa: "RIOPEC PNC PNC", ativo: "RIPC7L", tipo:"Ações" },
  { empresa: "RIOPEC PNC PND", ativo: "RIPC8L", tipo:"Ações" },
  { empresa: "COSAN LOG ON", ativo: "RLOG3", tipo:"Ações" },
  { empresa: "FUNDO BB RENDA DE PAPÉIS", ativo: "RNDP11", tipo:"Fundos Imobiliários" },
  { empresa: "RENOVA ON", ativo: "RNEW3", tipo:"Ações" },
  { empresa: "RENOVA PN", ativo: "RNEW4", tipo:"Ações" },
  { empresa: "RIO NEGRO", ativo: "RNGO11", tipo:"Fundos Imobiliários" },
  { empresa: "INDS ROMI ON", ativo: "ROMI3", tipo:"Ações" },
  { empresa: "ALFA ON", ativo: "RPAD3", tipo:"Ações" },
  { empresa: "ALFA PNA", ativo: "RPAD5", tipo:"Ações" },
  { empresa: "ALFA PNB", ativo: "RPAD6", tipo:"Ações" },
  { empresa: "PET MANGUINH ON", ativo: "RPMG3", tipo:"Ações" },
  { empresa: "RB CAPITAL RECEBÍVEIS IMOBILIÁRIOS", ativo: "RRCI11", tipo:"Fundos Imobiliários" },
  { empresa: "RSB 1", ativo: "RSBU11B", tipo:"Fundos Imobiliários" },
  { empresa: "ROSSI RESID ON", ativo: "RSID3", tipo:"Ações" },
  { empresa: "RB CAPITAL DESENVOLVIMENTO RESIDENCIAL III", ativo: "RSPD11", tipo:"Fundos Imobiliários" },
  { empresa: "RIO SULENSE ON", ativo: "RSUL3", tipo:"Ações" },
  { empresa: "RIO SULENSE PN", ativo: "RSUL4", tipo:"Ações" },
  { empresa: "VBI REITS FOF", ativo: "RVBI11", tipo:"Fundos Imobiliários" },
  { empresa: "SANTANDER AGÊNCIAS", ativo: "SAAG11", tipo:"Fundos Imobiliários" },
  { empresa: "SANTANDER PAPÉIS IMOBILIÁRIOS CDI", ativo: "SADI11", tipo:"Fundos Imobiliários" },
  { empresa: "SIA CORPORATE", ativo: "SAIC11B", tipo:"Fundos Imobiliários" },
  { empresa: "ANGELICA PNA PNA", ativo: "SAIS5L", tipo:"Ações" },
  { empresa: "SANTANDER BR ON", ativo: "SANB3", tipo:"Ações" },
  { empresa: "SANTANDER BR PN", ativo: "SANB4", tipo:"Ações" },
  { empresa: "SANEPAR ON", ativo: "SAPR3", tipo:"Ações" },
  { empresa: "SANEPAR PN", ativo: "SAPR4", tipo:"Ações" },
  { empresa: "SANTANDER RENDA DE ALUGUÉIS", ativo: "SARE11", tipo:"Fundos Imobiliários" },
  { empresa: "SABESP ON", ativo: "SBSP3", tipo:"Ações" },
  { empresa: "SÃO CARLOS ON", ativo: "SCAR3", tipo:"Ações" },
  { empresa: "SCP", ativo: "SCPF11", tipo:"Fundos Imobiliários" },
  { empresa: "SDI RIO BRAVO RENDA LOGÍSTICA", ativo: "SDIL11", tipo:"Fundos Imobiliários" },
  { empresa: "SER EDUCACIONAL ON", ativo: "SEER3", tipo:"Ações" },
  { empresa: "SÃO FERNANDO", ativo: "SFND11", tipo:"Fundos Imobiliários" },
  { empresa: "SPRINGS ON", ativo: "SGPS3", tipo:"Ações" },
  { empresa: "SHOPPING PARQUE DOM PEDRO", ativo: "SHDP11B", tipo:"Fundos Imobiliários" },
  { empresa: "MULTI SHOPPINGS", ativo: "SHOP11", tipo:"Fundos Imobiliários" },
  { empresa: "TIME FOR FUN ON", ativo: "SHOW3", tipo:"Ações" },
  { empresa: "SHOPPING PÁTIO HIGIENÓPOLIS", ativo: "SHPH11", tipo:"Fundos Imobiliários" },
  { empresa: "SCHULZ ON", ativo: "SHUL3", tipo:"Ações" },
  { empresa: "SCHULZ PN", ativo: "SHUL4", tipo:"Ações" },
  { empresa: "SLC AGRICOLA ON", ativo: "SLCE3", tipo:"Ações" },
  { empresa: "INNCORP ON", ativo: "SLCT3B", tipo:"Ações" },
  { empresa: "SARAIVA LIVR ON", ativo: "SLED1", tipo:"Ações" },
  { empresa: "SARAIVA LIVR", ativo: "SLED11", tipo:"Ações" },
  { empresa: "SARAIVA LIVR", ativo: "SLED12", tipo:"Ações" },
  { empresa: "SARAIVA LIVR", ativo: "SLED13", tipo:"Ações" },
  { empresa: "SARAIVA LIVR PN", ativo: "SLED2", tipo:"Ações" },
  { empresa: "SARAIVA LIVR ON", ativo: "SLED3", tipo:"Ações" },
  { empresa: "SARAIVA LIVR PN", ativo: "SLED4", tipo:"Ações" },
  { empresa: "SMART FIT PNA", ativo: "SMFT13", tipo:"Ações" },
  { empresa: "SMARTFIT ON", ativo: "SMFT3", tipo:"Ações" },
  { empresa: "SMART FIT PNB", ativo: "SMFT6", tipo:"Ações" },
  { empresa: "SMALL CAP", ativo: "SMLL11", tipo:"Ações" },
  { empresa: "SMILES ON", ativo: "SMLS3", tipo:"Ações" },
  { empresa: "SÃO MARTINHO ON", ativo: "SMTO3", tipo:"Ações" },
  { empresa: "SINOP AGRO QUIMICA PNA", ativo: "SNOP5L", tipo:"Ações" },
  { empresa: "SANSUY ON", ativo: "SNSY3", tipo:"Ações" },
  { empresa: "SANSUY PNA", ativo: "SNSY5", tipo:"Ações" },
  { empresa: "SANSUY PNB", ativo: "SNSY6", tipo:"Ações" },
  { empresa: "GRUPO DE MODA SOMA ON", ativo: "SOMA3", tipo:"Ações" },
  { empresa: "SONDOTECNICA ON", ativo: "SOND3", tipo:"Ações" },
  { empresa: "SONDOTECNICA PNA", ativo: "SOND5", tipo:"Ações" },
  { empresa: "SONDOTECNICA PNB", ativo: "SOND6", tipo:"Ações" },
  { empresa: "SPA", ativo: "SPAF11", tipo:"Fundos Imobiliários" },
  { empresa: "SPRINGER ON", ativo: "SPRI3", tipo:"Ações" },
  { empresa: "SPRINGER PNA", ativo: "SPRI5", tipo:"Ações" },
  { empresa: "SPRINGER PNB", ativo: "SPRI6", tipo:"Ações" },
  { empresa: "SP DOWNTOWN", ativo: "SPTW11", tipo:"Fundos Imobiliários" },
  { empresa: "SUCCESPAR VAREJO", ativo: "SPVJ11", tipo:"Fundos Imobiliários" },
  { empresa: "SINQIA ON", ativo: "SQIA3", tipo:"Ações" },
  { empresa: "SERMAR AGRO PNA PNA", ativo: "SRAG5L", tipo:"Ações" },
  { empresa: "SANTOS BRASIL ON", ativo: "STBP3", tipo:"Ações" },
  { empresa: "SANTANDER RECEBÍVEIS IMOBILIÁRIOS", ativo: "STFI11", tipo:"Fundos Imobiliários" },
  { empresa: "STATKRAFT ENERGIAS RENOV... ON", ativo: "STKF3", tipo:"Ações" },
  { empresa: "STARX", ativo: "STRX11", tipo:"Fundos Imobiliários" },
  { empresa: "STARA ON", ativo: "STTR3", tipo:"Ações" },
  { empresa: "SUINOS AVES NORDESTE SA ... PN", ativo: "SUIA4L", tipo:"Ações" },
  { empresa: "SUL AMERICA ON", ativo: "SULA3", tipo:"Ações" },
  { empresa: "SUL AMERICA PN", ativo: "SULA4", tipo:"Ações" },
  { empresa: "SUZANO PAPEL ON", ativo: "SUZB3", tipo:"Ações" },
  { empresa: "TAESA ON", ativo: "TAEE3", tipo:"Ações" },
  { empresa: "TAESA PN", ativo: "TAEE4", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "TASA13", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "TASA15", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "TASA17", tipo:"Ações" },
  { empresa: "FORJA TAURUS ON", ativo: "TASA3", tipo:"Ações" },
  { empresa: "FORJA TAURUS PN", ativo: "TASA4", tipo:"Ações" },
  { empresa: "TAURUS ARMAS ON", ativo: "TAUR", tipo:"Ações" },
  { empresa: "TAURUS ARMAS PN", ativo: "TAUR4", tipo:"Ações" },
  { empresa: "TERRA BRAVIA PN PN", ativo: "TBCC4L", tipo:"Ações" },
  { empresa: "TB OFFICE", ativo: "TBOF11", tipo:"Fundos Imobiliários" },
  { empresa: "TECNOSOLO ON", ativo: "TCNO3", tipo:"Ações" },
  { empresa: "TECNOSOLO PN", ativo: "TCNO4", tipo:"Ações" },
  { empresa: "TREECORP REAL ESTATE I", ativo: "TCPF11", tipo:"Fundos Imobiliários" },
  { empresa: "TECNISA ON", ativo: "TCSA3", tipo:"Ações" },
  { empresa: "TRANSCONTINENTAL HOTEIS ... PNA", ativo: "TCTN5L", tipo:"Ações" },
  { empresa: "TECHNOS ON", ativo: "TECN3", tipo:"Ações" },
  { empresa: "TEKA ON", ativo: "TEKA3", tipo:"Ações" },
  { empresa: "TEKA PN", ativo: "TEKA4", tipo:"Ações" },
  { empresa: "TELEBRAS ON", ativo: "TELB1", tipo:"Ações" },
  { empresa: "TELEBRAS PN", ativo: "TELB2", tipo:"Ações" },
  { empresa: "TELEBRAS ON", ativo: "TELB3", tipo:"Ações" },
  { empresa: "TELEBRAS PN", ativo: "TELB4", tipo:"Ações" },
  { empresa: "TELLUS DESENVOLVIMENTO LOGÍSTICO", ativo: "TELD11", tipo:"Fundos Imobiliários" },
  { empresa: "TENDA ON", ativo: "TEND3", tipo:"Ações" },
  { empresa: "TELLUS PROPERTIES", ativo: "TEPP11", tipo:"Fundos Imobiliários" },
  { empresa: "TERRA SANTA ON", ativo: "TESA12", tipo:"Ações" },
  { empresa: "TERRA SANTA ON", ativo: "TESA3", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF693", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF694", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF703", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF704", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF713", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF714", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF723", tipo:"Ações" },
  { empresa: "COMMON STOCK ON", ativo: "TF724", tipo:"Ações" },
  { empresa: "HEDGE TOP FOFII", ativo: "TFOF11", tipo:"Fundos Imobiliários" },
  { empresa: "TG ATIVO REAL", ativo: "TGAR11", tipo:"Fundos Imobiliários" },
  { empresa: "FD INAV IM ATIV RE COTAS", ativo: "TGAR12", tipo:"Ações" },
  { empresa: "TEGMA ON", ativo: "TGMA3", tipo:"Ações" },
  { empresa: "BM CYRELA THERA CORPORATE", ativo: "THRA11", tipo:"Fundos Imobiliários" },
  { empresa: "AES TIETÊ ON", ativo: "TIET3", tipo:"Ações" },
  { empresa: "AES TIETÊ PN", ativo: "TIET4", tipo:"Ações" },
  { empresa: "TIM ON", ativo: "TIMP3", tipo:"Ações" },
  { empresa: "TEKNO ON", ativo: "TKNO3", tipo:"Ações" },
  { empresa: "TEKNO PN", ativo: "TKNO4", tipo:"Ações" },
  { empresa: "TORDESILHAS EI", ativo: "TORD11", tipo:"Fundos Imobiliários" },
  { empresa: "TOURMALET I", ativo: "TORM11", tipo:"Fundos Imobiliários" },
  { empresa: "TOTVS ON", ativo: "TOTS3", tipo:"Ações" },
  { empresa: "TOURMALET II", ativo: "TOUR11", tipo:"Fundos Imobiliários" },
  { empresa: "TRIUNFO PART ON", ativo: "TPIS3", tipo:"Ações" },
  { empresa: "TRISUL ON", ativo: "TRIS3", tipo:"Ações" },
  { empresa: "TORRE NORTE", ativo: "TRNT11", tipo:"Fundos Imobiliários" },
  { empresa: "ISA CTEEP ON", ativo: "TRPL3", tipo:"Ações" },
  { empresa: "ISA CTEEP PN", ativo: "TRPL4", tipo:"Ações" },
  { empresa: "TRX REAL ESTATE II", ativo: "TRXB11", tipo:"Fundos Imobiliários" },
  { empresa: "TRX REAL ESTATE", ativo: "TRXF11", tipo:"Fundos Imobiliários" },
  { empresa: "TRANSINC", ativo: "TSNC11", tipo:"Fundos Imobiliários" },
  { empresa: "TECELAGEM TEXITA PNA", ativo: "TTEX5L", tipo:"Ações" },
  { empresa: "TUPY ON", ativo: "TUPY3", tipo:"Ações" },
  { empresa: "TBM TEXTIL BEZERRA MENEZ... PNA", ativo: "TXBZ5L", tipo:"Ações" },
  { empresa: "TEX RENAUX ON", ativo: "TXRX3", tipo:"Ações" },
  { empresa: "TEX RENAUX PN", ativo: "TXRX4", tipo:"Ações" },
  { empresa: "UBS BR RECEBÍVEIS", ativo: "UBSR11", tipo:"Fundos Imobiliários" },
  { empresa: "FII UBS CI", ativo: "UBSR12", tipo:"Ações" },
  { empresa: "FII UBS CI", ativo: "UBSR16", tipo:"Ações" },
  { empresa: "UNICASA ON", ativo: "UCAS3", tipo:"Ações" },
  { empresa: "ULTRAPAR ON", ativo: "UGPA3", tipo:"Ações" },
  { empresa: "UNIPAR ON", ativo: "UNIP3", tipo:"Ações" },
  { empresa: "UNIPAR PNA", ativo: "UNIP5", tipo:"Ações" },
  { empresa: "UNIPAR PNB", ativo: "UNIP6", tipo:"Ações" },
  { empresa: "UPTICK PARTICIPACOES ON", ativo: "UPKP3B", tipo:"Ações" },
  { empresa: "URBANIZA", ativo: "URBN11", tipo:"Fundos Imobiliários" },
  { empresa: "URCA PRIME RENDA", ativo: "URPR11", tipo:"Fundos Imobiliários" },
  { empresa: "USIMINAS ON", ativo: "USIM3", tipo:"Ações" },
  { empresa: "USIMINAS PNA", ativo: "USIM5", tipo:"Ações" },
  { empresa: "USIMINAS PNB", ativo: "USIM6", tipo:"Ações" },
  { empresa: "UTILITIES", ativo: "UTIL11", tipo:"Ações" },
  { empresa: "VALE ON", ativo: "VALE3", tipo:"Ações" },
  { empresa: "VECTIS JUROS REAL", ativo: "VCJR11", tipo:"Fundos Imobiliários" },
  { empresa: "VEREDA", ativo: "VERE11", tipo:"Fundos Imobiliários" },
  { empresa: "VALORA CRI ÍNDICE DE PREÇO", ativo: "VGIP11", tipo:"Fundos Imobiliários" },
  { empresa: "FII VALORA CRI INDICE DE...", ativo: "VGIP12", tipo:"Ações" },
  { empresa: "VALORA RE III", ativo: "VGIR11", tipo:"Fundos Imobiliários" },
  { empresa: "VIC DESENVOLVIMENTO - VINTAGE 20/21", ativo: "VIDS11", tipo:"Fundos Imobiliários" },
  { empresa: "VINCI INSTRUMENTOS FINANCEIROS", ativo: "VIFI11", tipo:"Fundos Imobiliários" },
  { empresa: "VINCI LOGÍSTICA", ativo: "VILG11", tipo:"Fundos Imobiliários" },
  { empresa: "FII VINCILOGCI EB", ativo: "VILG12", tipo:"Ações" },
  { empresa: "VINCI OFFICES", ativo: "VINO11", tipo:"Fundos Imobiliários" },
  { empresa: "VINCI SHOPPING CENTERS", ativo: "VISC11", tipo:"Fundos Imobiliários" },
  { empresa: "FII VINVI SCCI", ativo: "VISC13", tipo:"Ações" },
  { empresa: "VIVARA ON", ativo: "VIVA3", tipo:"Ações" },
  { empresa: "VIVER ON", ativo: "VIVR1", tipo:"Ações" },
  { empresa: "VIVER ON", ativo: "VIVR3", tipo:"Ações" },
  { empresa: "TELEF BRASIL ON", ativo: "VIVT3", tipo:"Ações" },
  { empresa: "TELEF BRASIL PN", ativo: "VIVT4", tipo:"Ações" },
  { empresa: "VALE BONITO PNB", ativo: "VLBN6L", tipo:"Ações" },
  { empresa: "VALID ON", ativo: "VLID3", tipo:"Ações" },
  { empresa: "VECTOR QUELUZ LAJES CORPORATIVAS", ativo: "VLJS11", tipo:"Fundos Imobiliários" },
  { empresa: "VILA OLÍMPIA CORPORATE", ativo: "VLOL11", tipo:"Fundos Imobiliários" },
  { empresa: "VOTORANTIM SECURITIES MASTER", ativo: "VOTS11", tipo:"Fundos Imobiliários" },
  { empresa: "POLO SHOPPING INDAIATUBA", ativo: "VPSI11", tipo:"Fundos Imobiliários" },
  { empresa: "FATOR VERITÀ", ativo: "VRTA11", tipo:"Fundos Imobiliários" },
  { empresa: "FII FATOR VE", ativo: "VRTA12", tipo:"Ações" },
  { empresa: "VOTORANTIM SECURITIES", ativo: "VSEC11", tipo:"Fundos Imobiliários" },
  { empresa: "VOTORANTIM SHOPPING", ativo: "VSHO11", tipo:"Fundos Imobiliários" },
  { empresa: "FERROVIA CENTRO ATL ON", ativo: "VSPT3", tipo:"Ações" },
  { empresa: "FERROVIA CENTRO ATL PN", ativo: "VSPT4", tipo:"Ações" },
  { empresa: "VOTORANTIM LOGÍSTICA", ativo: "VTLT11", tipo:"Fundos Imobiliários" },
  { empresa: "VOTORANTIM PATRIMONIAL V", ativo: "VTPA11", tipo:"Fundos Imobiliários" },
  { empresa: "FII PLUS", ativo: "VTPL11", tipo:"Fundos Imobiliários" },
  { empresa: "PARKING PARTNERS", ativo: "VTVI11", tipo:"Fundos Imobiliários" },
  { empresa: "VOTORANTIM PATRIMONIAL XII", ativo: "VTXI11", tipo:"Fundos Imobiliários" },
  { empresa: "VULCABRAS ON", ativo: "VULC3", tipo:"Ações" },
  { empresa: "VIA VAREJO ON", ativo: "VVAR3", tipo:"Ações" },
  { empresa: "V2 PROPERTIES", ativo: "VVPR11", tipo:"Fundos Imobiliários" },
  { empresa: "VX XVI", ativo: "VXXV11", tipo:"Fundos Imobiliários" },
  { empresa: "WEG ON", ativo: "WEGE3", tipo:"Ações" },
  { empresa: "WHIRLPOOL ON", ativo: "WHRL3", tipo:"Ações" },
  { empresa: "WHIRLPOOL PN", ativo: "WHRL4", tipo:"Ações" },
  { empresa: "WIZ S.A ON", ativo: "WIZS3", tipo:"Ações" },
  { empresa: "WLM ON", ativo: "WLMM3", tipo:"Ações" },
  { empresa: "WLM PN", ativo: "WLMM4", tipo:"Ações" },
  { empresa: "WM RB CAPITAL", ativo: "WMRB11B", tipo:"Fundos Imobiliários" },
  { empresa: "WEST PLAZA", ativo: "WPLZ11", tipo:"Fundos Imobiliários" },
  { empresa: "OURINVEST RE I", ativo: "WTSP11B", tipo:"Fundos Imobiliários" },
  { empresa: "XINGUARA IND PNA PNA", ativo: "XING5L", tipo:"Ações" },
  { empresa: "XP CRÉDITO", ativo: "XPCI11", tipo:"Fundos Imobiliários" },
  { empresa: "FII XP CREDITO", ativo: "XPCI12", tipo:"Ações" },
  { empresa: "XP CORPORATE MACAÉ", ativo: "XPCM11", tipo:"Fundos Imobiliários" },
  { empresa: "XP RECEBÍVEIS", ativo: "XPGA11", tipo:"Fundos Imobiliários" },
  { empresa: "XP HOTÉIS (COTA SÊNIOR)", ativo: "XPHT11", tipo:"Fundos Imobiliários" },
  { empresa: "XP HOTÉIS (COTA ORDINÁRIA)", ativo: "XPHT12", tipo:"Fundos Imobiliários" },
  { empresa: "FII XP HOT CI", ativo: "XPHT14", tipo:"Ações" },
  { empresa: "XP INDUSTRIAL", ativo: "XPIN11", tipo:"Fundos Imobiliários" },
  { empresa: "FII XP INDL CI ER", ativo: "XPIN12", tipo:"Ações" },
  { empresa: "XP LOG", ativo: "XPLG11", tipo:"Fundos Imobiliários" },
  { empresa: "XP LOG FII COTAS", ativo: "XPLG12", tipo:"Ações" },
  { empresa: "XP MALLS", ativo: "XPML11", tipo:"Fundos Imobiliários" },
  { empresa: "XP MALLS FD INV", ativo: "XPML13", tipo:"Ações" },
  { empresa: "XP PROPERTIES", ativo: "XPPR11", tipo:"Fundos Imobiliários" },
  { empresa: "XP SELECTION", ativo: "XPSF11", tipo:"Fundos Imobiliários" },
  { empresa: "TRX EDIFÍCIOS CORPORATIVOS", ativo: "XTED11", tipo:"Fundos Imobiliários" },
  { empresa: "XAVANTE AGRO PNA PNA", ativo: "XVTE5L", tipo:"Ações" },
  { empresa: "ESTACIO PART ON", ativo: "YDUQ3", tipo:"Ações" }

]
